### PR TITLE
fix: formatting of ISO8601Date.java

### LINKED ISSUE #1605: Delegate Date string formatting to a single DateUtil class
**Actual Behaviour**

Currently, we are manually parsing dates in various sections of app, where some ignore timezone and some use another mechanism to parse it. 

**Expected Behaviour**

For an event-based application, it is trivial to do correct and standard date conversions so it must happen in a single tested class which correctly handles all edge cases and TZ information correctly

**Would you like to work on the issue?**

Yes, but if anyone else is interested, he/she may take it up

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1605 

Changes: 
Formatted the ISO8601Date.java class.

Screenshots for the change: 

-

### CODE REVIEW

**Comment by arp95** [comment]
@iamareebjamal 
please check!

File: android/app/src/main/java/org/fossasia/openevent/widget/BookmarkWidgetRemoteViewsService.java [hunk 1]
```diff
@@ -17,7 +17,11 @@
 import org.fossasia.openevent.utils.ConstantStrings;
 import org.fossasia.openevent.utils.ISO8601Date;
 
+import java.sql.Time;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/widget/BookmarkWidgetRemoteViewsService.java]: Please remove

**Comment by arp95** [comment]
@iamareebjamal please have a look now.

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 2]
```diff
@@ -199,13 +205,16 @@ private void updateSession() {
...
-                + ISO8601Date.getTimeZoneDateString(ISO8601Date.getDateObject(session.getStartTime())).split(",")[3];
-        String endTime = ISO8601Date.getTimeZoneDateString(ISO8601Date.getDateObject(session.getEndTime())).split(",")[2] + ","
-                + ISO8601Date.getTimeZoneDateString(ISO8601Date.getDateObject(session.getEndTime())).split(",")[3];
+        simpleDateFormat.setTimeZone(eventTimeZone);
+        String date = null;
+        String startTime = null;
+        String endTime = null;
+
+        if(session.getStartTime()!=null) {
+            date = ISO8601Date.getTimeZoneDateStringFromString(session.getStartTime() + "Z", simpleDateFormat, eventTimeZone).split(",")[0] + "," + ISO8601Date.getTimeZoneDateStringFromString(session.getStartTime() + "Z", simpleDateFormat, eventTimeZone).split(",")[1];
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: This can be simplified. The issue I created was to handle these complex formatting in a Util class, so the views just have to call a single method to get a formatted date

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 3]
```diff
@@ -366,9 +377,9 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 intent.setType("vnd.android.cursor.item/event");
                 intent.putExtra(CalendarContract.Events.TITLE, title);
                 intent.putExtra(CalendarContract.Events.DESCRIPTION, session.getDescription());
-                intent.putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME, ISO8601Date.getDateObject(session.getStartTime()).getTime());
-                intent.putExtra(CalendarContract.EXTRA_EVENT_END_TIME,
-                        ISO8601Date.getDateObject(session.getEndTime()).getTime());
+                simpleDateFormat.setTimeZone(eventTimeZone);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: The proposed `DateUtil` class should automatically handle timezone information

**Comment by arp95** [comment]
actually i wanted to simplify some stuff but that would have led to hardcoding which i dont want in the class. having a look again to simplify stuff.

**Comment by iamareebjamal** [comment]
You can pass a date format string to the dateutils method, and it will handle everything from there

**Comment by arp95** [comment]
@iamareebjamal is this fine? will squash the commits once its done.

**Comment by arp95** [comment]
@iamareebjamal please ignore the codacy. i will changes for that. just see the code if thats fine.

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 4]
```diff
@@ -410,9 +411,7 @@ private void syncComplete() {
 
                         // Event successfully loaded, set data downloaded to true
                         sharedPreferences.edit().putBoolean(ConstantStrings.IS_DOWNLOAD_DONE, true).apply();
-
-                        getDaysBetweenDates(
-                                ISO8601Date.getDateObject(event.getStart()), ISO8601Date.getDateObject(event.getEnd()))
+                        getDaysBetweenDates(ISO8601Date.getTimeZoneDateFromString(event.getStart(), ISO8601Date.getTimeZoneOfEvent()), ISO8601Date.getTimeZoneDateFromString(event.getEnd(), ISO8601Date.getTimeZoneOfEvent()))
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: You can create a `DateUtils` method getDateFromString which will be timezone aware and automatically call getTimeZoneofEvent in its implementation. 

Views should just straightforward call the getter and the DateUtils class should handle everything itself without views having to worry about timezone and other things

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 5]
```diff
@@ -199,13 +203,15 @@ private void updateSession() {
...
-        String startTime = ISO8601Date.getTimeZoneDateString(ISO8601Date.getDateObject(session.getStartTime())).split(",")[2] + ","
-                + ISO8601Date.getTimeZoneDateString(ISO8601Date.getDateObject(session.getStartTime())).split(",")[3];
-        String endTime = ISO8601Date.getTimeZoneDateString(ISO8601Date.getDateObject(session.getEndTime())).split(",")[2] + ","
-                + ISO8601Date.getTimeZoneDateString(ISO8601Date.getDateObject(session.getEndTime())).split(",")[3];
+        String date = null;
+        String startTime = null;
+        String endTime = null;
+
+        if(session.getStartTime()!=null) {
+            startTime = ISO8601Date.getStartDateString(session.getStartTime() + "Z");
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Same here, reduce to a simple getter call

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 6]
```diff
@@ -366,9 +372,8 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 intent.setType("vnd.android.cursor.item/event");
                 intent.putExtra(CalendarContract.Events.TITLE, title);
                 intent.putExtra(CalendarContract.Events.DESCRIPTION, session.getDescription());
-                intent.putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME, ISO8601Date.getDateObject(session.getStartTime()).getTime());
-                intent.putExtra(CalendarContract.EXTRA_EVENT_END_TIME,
-                        ISO8601Date.getDateObject(session.getEndTime()).getTime());
+                intent.putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME, ISO8601Date.get24HourTimeFromString(session.getStartTime() + "Z", ISO8601Date.getTimeZoneOfEvent()));
+                intent.putExtra(CalendarContract.EXTRA_EVENT_END_TIME, ISO8601Date.get24HourTimeFromString(session.getEndTime(), ISO8601Date.getTimeZoneOfEvent()));
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Big lines like this are the reason we are creating a new API

**Comment by arp95** [comment]
@iamareebjamal
if you check the methods, i pass the timezone and the string to get the result. do you want me to simplilfy then that?

**Comment by arp95** [comment]
just to clear it out. why i am passng timezone is becaue in testing i want to pass my own timezone. thats why i created another parameter for it. it should be fine right?

**Comment by iamareebjamal** [comment]
@arp95 The strategy should be for view to just call appropriate getter and get the requested string. That's why I asked to create a DateUtils class where every detail will be abstracted. That invoked function will call the the ISODate static function and return the appropriate result. This way we will just statically set the timezone of app ad check if all DateUtils methods are working correctly.
Like

assertEquals(DateUtils.getDate("xyz"), "xyz-yy");

This will also allow us to change the implementation of these methods any time without requiring to touch the code even once because the view will only be calling DateUtils method.

**Comment by iamareebjamal** [comment]
An example of half the class I wrote while working on this. https://hastebin.com/fagucoducu.vbs

You just have to add a parameter in these calls to make it configurable

**Comment by arp95** [comment]
i know you wanted to pass one parameter. but when i will do date testing in that i have to test the value returned by the function by a value which i know already. so lets say i enable getTimeZoneOfEvent within function in that case wont it the date testing.get stuck?

**Comment by iamareebjamal** [comment]
Have a static variable to store timezone, load it initially using the app timezone
Create a static function setTimeZone and call it with custom timezones each time you want to test for different timezone

**Comment by arp95** [comment]
for each part that is activity or fragment if i call setTimeZone will it be fine apart from normal calls?

**Comment by iamareebjamal** [comment]
You just will have to call it once throughout the app and for tests, call it every time you want to change timezone.

**Comment by iamareebjamal** [comment]
The timezone of the app will not change throughout its run, so setting it once will be enough

**Comment by arp95** [comment]
no thats where i was getting confused. we have a setting for local timezone in settings right. for hat i am referring.

**Comment by iamareebjamal** [comment]
You load from preference once in the first run of the static method, and whenever the setting is changes, you set the appropriate timezone

**Comment by arp95** [comment]
so move that part in each method right?
checking whether user set the local timezone or not?

**Comment by arp95** [comment]
wait sending you the changes in 1-2 hours.

**Comment by arp95** [comment]
@iamareebjamal 
now working! hopefully the api is fine now. please check!

**Comment by iamareebjamal** [comment]
@arp95 Sorry for late reply. My laptop broke. Having a look

**Comment by iamareebjamal** [comment]
@arp95 Perfect! Just remove the warnings and we are good to go

Also, you may start writing tests for it for #1566

**Comment by arp95** [comment]
sure. working on it ASAP.

**Comment by arp95** [comment]
@iamareebjamal 
please merge so that i can wok on date tests.

**Comment by mahikaw** [comment]
LGTM @arp95 except for a few blank lines additions and deletions here and there.

**Comment by arp95** [comment]
@Shailesh351 please review the pr again and tell if other changes are needed to be made in the meantime.
making these changes ASAP.

**Comment by arp95** [comment]
@Shailesh351 is it fine now?

**Comment by iamareebjamal** [comment]
@Shailesh351 Please check if any discrepancies remain on your side?

File: android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java [hunk 7]
```diff
@@ -73,8 +74,10 @@ public boolean onPreferenceChange(Preference preference, Object o) {
         } else if (preference.getKey().equals(getResources().getString(R.string.timezone_mode_key))) {
             if (o.equals(false)) {
                 timezonePreference.setChecked(false);
+                ISO8601Date.setTimeZone();
             } else if (o.equals(true)) {
                 timezonePreference.setChecked(true);
+                ISO8601Date.setTimeZoneDefault();
```
Comment (rohanagarwal94) [inline android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java]: please use `else` if only two cases are required

File: android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java [hunk 8]
```diff
@@ -3,135 +3,216 @@
...
-        String final1 = iso8601String + "Z";
+    //return date string of a specified timezone from a given date string
+    public static String getTimeZoneDateStringFromString(String dateString) {
+        String currentDate = dateString + "Z";
+        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.getDefault());
+        simpleDateFormat.setTimeZone(TimeZone.getDefault());
+        Date date = null;
+        String date_string = null;
+        try {
+            if(dateString!=null){
```
Comment (rohanagarwal94) [inline android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java]: please insert a space before the starting curly braces in `if` statement. Please do so in every subsequent place possible.

**Comment by arp95** [comment]
@rohanagarwal94 is it fine now?

**Comment by iamareebjamal** [comment]
@Shailesh351 Please have a last look at the issues you were facing and approve if they are gone

**Comment by Shailesh351** [comment]
Sorry for the delay had fever tomorrow,

@arp95 @iamareebjamal @rohanagarwal94 
As per https://eventyay.com/e/45da88b7/schedule/ 

Actual time of FOSSASIA welcome event is **09:00 Asia/singapore(GMT +08:00)**
But it is showing **11:30 (GMT +08:00)** in app. And it is critical issue

May be it is because of setting timezone in SDF when there is no need or timezone is not in SDF set when there is need.

**Comment by arp95** [comment]
is it a fault from my side?
let me have a look.

**Comment by Shailesh351** [comment]
@arp95 

Look at https://hastebin.com/xuwazidefi.js 
I have Changed getTimeZoneOfEvent() method and added getTimeZone() method.
Renamed some variables.

You can make one method for last four method which will take two format strings and return formatted string

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 please have a final look so that i can start working on date tests.

**Comment by iamareebjamal** [comment]
@arp95 You may start

File: android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java [hunk 9]
```diff
@@ -3,135 +3,222 @@
...
-        return dateFormat.format(date);
+    //return timezone of event
+    public static TimeZone getEventTimeZone() {
+        String eventTimeZone = PreferenceManager.getDefaultSharedPreferences(OpenEventApp.getAppContext()).getString(ConstantStrings.TIMEZONE, "");
+        return ISO8601Date.getTimeZoneById(eventTimeZone);
     }
 
-    public static Date getTimeZoneDate(final Date date) {
+    //return timezone of the event
+    public static TimeZone getTimeZoneOfEvent() {
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java]: Here `getTimeZoneOfEvent()` should be `getTimeZone()`

File: android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java [hunk 10]
```diff
@@ -3,135 +3,222 @@
...
+        String eventTimeZone;
 
-        SimpleDateFormat dateFormat = new SimpleDateFormat("EE, dd MMM yyyy, HH:mm, z", Locale.getDefault());
-        dateFormat.setTimeZone(getTimezone());
-        String DateToStr = dateFormat.format(date);
-        return date;
+        //sets timezone to event timezone
+        eventTimeZone = PreferenceManager.getDefaultSharedPreferences(OpenEventApp.getAppContext()).getString(ConstantStrings.TIMEZONE, "");
+        //sets timezone to local if user has selected
+        String local_timezone = OpenEventApp.getAppContext().getString(R.string.timezone_mode_key);
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java]: Rename `local_timezone` to `isLocalTimeZone`

File: android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java [hunk 11]
```diff
@@ -3,135 +3,222 @@
...
+        simpleDateFormat.setTimeZone(getEventTimeZone());
         Date date = null;
+        String date_string = null;
         try {
-            date = format.parse(final1);
+            if(dateString!=null) {
+                date = simpleDateFormat.parse(currentDate);
+                SimpleDateFormat dateFormat = new SimpleDateFormat("EE, dd MMM yyyy, HH:mm, z", Locale.getDefault());
+                dateFormat.setTimeZone(timeZone);
+                date_string = dateFormat.format(date);
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java]: Rename `date_string` to `formatedDateString`

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 have a look.

**Comment by iamareebjamal** [comment]
@the-dagger Please take a look

**Comment by arp95** [comment]
@iamareebjamal really sorry for this. just used eventTimeZone as a variable so that it can help me with date tests.

**Comment by arp95** [comment]
now working fine. started with date tests.

**Comment by arp95** [comment]
@the-dagger please have a look

**Comment by arp95** [comment]
@iamareebjamal have resolved conflicts. please take a look

File: android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java (hunk 7 above)
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java]: Yeah @arp95 I think although this is not your change but it can be fixed to be just `else` and also rename the `o` variable while you are at it. Sorry for so many requirement changes

**Comment by arp95** [comment]
@iamareebjamal made the changes.
