### PR TITLE
fix: improve logic of onBackPressed for Fragments

### LINKED ISSUE #686: improve on back pressed logic to remove bugs
**Describe the bug**
- Last fragment is set on back pressed in event fragment
- Event fragment directly set from settings fragment

**To Reproduce**
1. One search/favorite/profile fragment
2. Press back again after the event fragment
3. Last fragment is set
4. Open settings fragment
5. Events are open instead of open profile fragment

**Expected behavior**
- All main fragment should set event fragment on back pressed
- Settings fragment should set profile fragment on back pressed

**Smartphone Info:**
|Device         |Mi Max 2|
|Android Version| Nougat 7.1    |

**Additional context**
blank diagram 3

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #686 

Changes: MainActivity.kt

blank diagram 3

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 1]
```diff
@@ -126,13 +126,25 @@ class MainActivity : AppCompatActivity() {
...
-            navigation.selectedItemId = navigation_events
-        } else {
+        if (rootFragment is EventDetailsFragment) {
             super.onBackPressed()
+            return
         }
+
+        val currentFragment = this.supportFragmentManager.findFragmentById(R.id.frameContainer)
+        when(currentFragment) {
+            is EventsFragment -> finish()
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: This solution will work but the app should exit even without explicitly using this method.
I guess it is because the logic of `loadFragment` was changed. Earlier `addToBackStack` wasn't used in that method.

**Comment by iamareebjamal** [comment]
First let us decide what the navigation flow should be. Can someone comment the expected navigation flow for the app

**Comment by liveHarshit** [comment]
> First let us decide what the navigation flow should be. Can someone comment the expected navigation flow for the app

Okay, but here I follow same as Eventbrite :smile:

**Comment by iamareebjamal** [comment]
Let's mention that here so other contributors from future can adhere to it

**Comment by liveHarshit** [comment]
> Let's mention that here so other contributors from future can adhere to it

Added in PR description.

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 2]
```diff
@@ -121,18 +121,28 @@ class MainActivity : AppCompatActivity() {
     private fun loadFragment(fragment: Fragment) {
         supportFragmentManager.beginTransaction()
                 .replace(R.id.frameContainer, fragment, fragment::class.java.name)
-                .addToBackStack(null)
                 .commit()
     }
 
     override fun onBackPressed() {
-        val currentFragment = this.supportFragmentManager.findFragmentById(R.id.frameContainer)
+
```
Comment (simarsingh24) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: extra feed

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 3]
```diff
@@ -121,18 +121,28 @@ class MainActivity : AppCompatActivity() {
...
         val rootFragment = this.supportFragmentManager.findFragmentById(R.id.rootLayout)
-        if (currentFragment !is EventsFragment && rootFragment !is EventDetailsFragment) {
-            loadFragment(EventsFragment())
-            navigation.selectedItemId = navigation_events
-        } else {
+        if (rootFragment is EventDetailsFragment) {
             super.onBackPressed()
+            return
         }
+
```
Comment (simarsingh24) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: same

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 4]
```diff
@@ -121,18 +121,28 @@ class MainActivity : AppCompatActivity() {
...
 
     override fun onBackPressed() {
-        val currentFragment = this.supportFragmentManager.findFragmentById(R.id.frameContainer)
+
         val rootFragment = this.supportFragmentManager.findFragmentById(R.id.rootLayout)
-        if (currentFragment !is EventsFragment && rootFragment !is EventDetailsFragment) {
-            loadFragment(EventsFragment())
-            navigation.selectedItemId = navigation_events
-        } else {
+        if (rootFragment is EventDetailsFragment) {
```
Comment (simarsingh24) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: why is this needed if no case is true below super.onBackPressed will be executed. Please check and avoid repetitions

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt (hunk 2 above)
Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Not extra... Here I separate methods for root container and frame container.

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt (hunk 3 above)
Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Same

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt (hunk 2 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: No Kotlin style guide tells you to add a line feed at the start of method body

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt (hunk 4 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Because of the return

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 5]
```diff
@@ -121,18 +121,28 @@ class MainActivity : AppCompatActivity() {
...
             super.onBackPressed()
+            return
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Use else

**Comment by liveHarshit** [comment]
Updated

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 6]
```diff
@@ -121,18 +121,24 @@ class MainActivity : AppCompatActivity() {
     private fun loadFragment(fragment: Fragment) {
         supportFragmentManager.beginTransaction()
                 .replace(R.id.frameContainer, fragment, fragment::class.java.name)
-                .addToBackStack(null)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Why is this removed?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: With this, App will not exit with `super.onBackPressed()`. Need to use `finish()` explicitly for exit the app.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Without this, we don't have state saving of fragments

**Comment by liveHarshit** [comment]
Updated. Now, one bug is there due to `addToBackStack(null)` which already has PR #629

**Comment by simarsingh24** [comment]
@liveHarshit  please update on this pr's status

**Comment by liveHarshit** [comment]
Due to my college examination, I'm not able to work on the PR. I'm really sorry about that. I will update the PR asap. And as I mentioned in my last comment, I it a right solution?

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 7]
```diff
@@ -126,13 +126,20 @@ class MainActivity : AppCompatActivity() {
     }
 
     override fun onBackPressed() {
-        val currentFragment = this.supportFragmentManager.findFragmentById(R.id.frameContainer)
```
Comment (simarsingh24) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: why is this removed and then written again? Rest LGTM 👍

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: First I declare root fragment then current fragment in sequence.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Updated.
