### PR TITLE
fix: stop reloading old image when rotating on EditProfileFragment

### LINKED ISSUE #1016: User Details and Image is lost in screen rotation
**Describe the bug**
When the user edits his/her profile, then the entered data and loaded image is not retained when the screen is rotated.

**To Reproduce**
Profile -> Edit -> Enter details, select an image and rotate the screen.

**Expected behavior**
Entered data and image should retain

**Screenshots**
videotogif_2019 02 03_17 12 19

**Smartphone Info:**
Redmi Note5 pro 8.1 Oreo

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by anhanh11001**
Details:
When the screen is rotated, if a new image is chosen, the URI of that image is saved on onSaveInstanceState and then reload when the view is created after rotating

Fixes #1016 (The part where EditText is not retained in 1016 issue is already resolved in other PR and merged)

Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Use view model. No need for saved instance state

**Comment by anhanh11001** [comment]
@iamareebjamal  I have used the viewModel, please take a look

File: app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt [hunk 1]
```diff
@@ -19,6 +19,7 @@ class ProfileViewModel(private val authService: AuthService) : ViewModel() {
     val user: LiveData<User> = mutableUser
     private val mutableError = SingleLiveEvent<String>()
     val error: LiveData<String> = mutableError
+    var avatarPicked = MutableLiveData<String>()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt]: Should be val
