### PR TITLE
fix: Retain ticket details' visibility after screen rotation

### LINKED ISSUE #1286: Hide/View is not retained after rotating screen
**Describe the bug**
When you are opening the detail section on price by (view), it's closed after rotating devices. So the current state is not retained.

**Screenshots**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anhanh11001**
Details:
Ticket Details Visibility is subscribed to the View Model as a boolean so that it survives after screen rotation

Fixes #1286 

Screenshots for the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt [hunk 1]
```diff
@@ -143,6 +144,14 @@ class AttendeeViewModel(
         )
     }
 
+    fun updateTicketDetailsVisibility() {
+        if (ticketDetailsVisibility.value == null) {
+            ticketDetailsVisibility.value = false
+        } else {
+            ticketDetailsVisibility.value = !ticketDetailsVisibility.value!!
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt]: Please do not use non-null assertion.

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt]: I will fix this. And some of my PRs keep having build fail because UndocumentedPublicFunction error, so how should I avoid this or does that mean I have to write some documentations/comments for that ?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt]: I think build will not fail for UndocumentedPublicFunction. Codacy will fail, which is okay.
