### PR TITLE
fix: duplicate APKs bug in APK branch

### LINKED ISSUE #528: update apk script to fix duplicate APKs bug
working on it 👍

### PR DESCRIPTION
**Pull request by simarsingh24**
fixes #528

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Correct the apk names below as well if the old names are being used

File: scripts/update-apk.sh [hunk 1]
```diff
@@ -43,15 +43,15 @@ if [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ]; then
...
+		mv $file open-event-dev-${file%%}
 	done
 fi
 
 # Signing Apps
 
 if [ "$TRAVIS_BRANCH" == "$PUBLISH_BRANCH" ]; then
     echo "Push to master branch detected, signing the app..."
-    cp app-release-unsigned.apk app-release-unaligned.apk
+    cp open-event-master-app-playStore-release-unsigned.apk app-release-unaligned.apk
```
Comment (simarsingh24) [inline scripts/update-apk.sh]: @iamareebjamal this is the change you meant right?

Comment (iamareebjamal) [reply scripts/update-apk.sh]: Yes, and below

Comment (simarsingh24) [reply scripts/update-apk.sh]: updated

File: scripts/update-apk.sh [hunk 2]
```diff
@@ -53,7 +53,7 @@ if [ "$TRAVIS_BRANCH" == "$PUBLISH_BRANCH" ]; then
     echo "Push to master branch detected, signing the app..."
     cp open-event-master-app-playStore-release-unsigned.apk app-release-unaligned.apk
 	jarsigner -verbose -tsa http://timestamp.comodoca.com/rfc3161 -sigalg SHA1withRSA -digestalg SHA1 -keystore ../scripts/key.jks -storepass $STORE_PASS -keypass $KEY_PASS app-release-unaligned.apk $ALIAS
-	${ANDROID_HOME}/build-tools/27.0.3/zipalign -v -p 4 app-release-unaligned.apk app-release.apk
+	${ANDROID_HOME}/build-tools/27.0.3/zipalign -v -p 4 app-release-unaligned.apk open-event-master-app-playStore-release.apk
```
Comment (iamareebjamal) [inline scripts/update-apk.sh]: Remaining

File: scripts/update-apk.sh (hunk 1 above)
Comment (iamareebjamal) [reply scripts/update-apk.sh]: More remaining

File: scripts/update-apk.sh (hunk 2 above)
Comment (simarsingh24) [reply scripts/update-apk.sh]: `cp open-event-master-app-playStore-release-unsigned.apk app-release-unaligned.apk` this will copy and rename the apk and then in last line we are using the latter, what change is remaining? 🤔

Comment (iamareebjamal) [reply scripts/update-apk.sh]: `app-release-unaligned.apk` And many more

Comment (simarsingh24) [reply scripts/update-apk.sh]: okay

**Comment by simarsingh24** [comment]
@iamareebjamal please review

File: scripts/update-apk.sh [hunk 3]
```diff
@@ -43,17 +43,17 @@ if [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ]; then
...
 fi
 
 # Signing Apps
 
 if [ "$TRAVIS_BRANCH" == "$PUBLISH_BRANCH" ]; then
     echo "Push to master branch detected, signing the app..."
-    cp app-release-unsigned.apk app-release-unaligned.apk
-	jarsigner -verbose -tsa http://timestamp.comodoca.com/rfc3161 -sigalg SHA1withRSA -digestalg SHA1 -keystore ../scripts/key.jks -storepass $STORE_PASS -keypass $KEY_PASS app-release-unaligned.apk $ALIAS
-	${ANDROID_HOME}/build-tools/27.0.3/zipalign -v -p 4 app-release-unaligned.apk app-release.apk
+    cp open-event-master-app-playStore-release-unsigned.apk app-playStore-release-unaligned.apk
```
Comment (iamareebjamal) [inline scripts/update-apk.sh]: `app-playStore-release-unaligned.apk` Wrong format

Comment (simarsingh24) [reply scripts/update-apk.sh]: should i rename it to  `open-event-master-app-playStore-release-unaligned.apk` ?

Comment (iamareebjamal) [reply scripts/update-apk.sh]: Yes

Comment (simarsingh24) [reply scripts/update-apk.sh]: updated

**Comment by iamareebjamal** [comment]
Confirm that apk is being generated, signed and uploaded

**Comment by simarsingh24** [comment]
@iamareebjamal the unaligned an release apks were not generated
