### PR TITLE
fix: set default value of qty to zero

### LINKED ISSUE #229: default value of tickets qty spinner should be zero
working on it

### PR DESCRIPTION
**Pull request by nikit19**
fixes #229 
screenshot_20180630-200154

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt [hunk 1]
```diff
@@ -14,6 +14,7 @@ class TicketViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
 
         if (ticket.minOrder > 0 && ticket.maxOrder > 0) {
             val spinnerList = ArrayList<String>()
+            spinnerList.add(Integer.toString(0))
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt]: "0"

Comment (nikit19) [reply app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt]: PR Updated
