### PR TITLE
fix: Add JSON payload images in apk

### LINKED ISSUE #1610: Adding speaker images in apk
**Actual Behaviour**

As discussed in issue #1593  , our main aim is to allow event organiser to upload images either manually or using server code. Adding relevant code in generator.py .

**Expected Behaviour**

If images/speakers have speaker images they should be in the res folder.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/27

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1610 

Changes: 
- Add speaker and sponsor images in apk
- Add option to load images from asset URI via Picasso
- Add tests for URI converter

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arp95 @mahikaw @Shailesh351 You may review as well

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 @mahikaw @shreyasnbhat @rohanagarwal94 Please review

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionSpeakerListAdapter.java [hunk 1]
```diff
@@ -45,14 +47,19 @@ public RecyclerViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
     public void onBindViewHolder(RecyclerViewHolder holder, final int position) {
         final Speaker current = getItem(position);
 
-        String thumbnail = current.getThumbnail();
+        String thumbnail = Utils.getSpeakerImageUri(current.getThumbnail());
+        if (thumbnail == null)
+            thumbnail = Utils.getSpeakerImageUri(current.getPhoto());
```
Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionSpeakerListAdapter.java]: shouldnt it be current.getThumbnail() ?

File: android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java [hunk 2]
```diff
@@ -118,14 +120,18 @@ public void onBindViewHolder(RecyclerViewHolder holder, final int position) {
         }
 
 
-        String thumbnail = current.getThumbnail();
+        String thumbnail = Utils.getSpeakerImageUri(current.getThumbnail());
+        if (thumbnail == null)
+            thumbnail = Utils.getSpeakerImageUri(current.getPhoto());
```
Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java]: same as above. the thumbnail should be fetched using getThumbnail() .

Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java]: if its null, should we fetch from photo?

File: android/app/src/main/java/org/fossasia/openevent/utils/Utils.java [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+            return null;
+
+        if(uri.startsWith("http") || uri.startsWith("https"))
+            return uri;
+
+        if(uri.startsWith("/"))
+            return "file:///android_asset" + uri;
+
+        return null;
+    }
```
Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/utils/Utils.java]: nice work!

File: android/app/src/test/java/org/fossasia/openevent/utils/SpeakerImageUriTest.java [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+        String https_url = "http://website.ext/resource.ext";
+
+        assertEquals(url, Utils.getSpeakerImageUri(url));
+        assertEquals(https_url, Utils.getSpeakerImageUri(https_url));
+    }
+
+    @Test
+    public void shouldReturnAssetUri() throws Exception {
+        String uri = "/images/speakers/JohnWick.jpg";
+        String sponsors_uri = "/images/sponsors/Google_1.png";
```
Comment (arp95) [inline android/app/src/test/java/org/fossasia/openevent/utils/SpeakerImageUriTest.java]: shouldnt the test be lile this. we fetch an image available instead of hardcoding a uri of an image?
because it might not be available.

File: android/app/src/test/java/org/fossasia/openevent/utils/SpeakerImageUriTest.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+
+        assertEquals("file:///android_asset/images/speakers/JohnWick.jpg", Utils.getSpeakerImageUri(uri));
+        assertEquals("file:///android_asset/images/sponsors/Google_1.png", Utils.getSpeakerImageUri(sponsors_uri));
```
Comment (Shailesh351) [inline android/app/src/test/java/org/fossasia/openevent/utils/SpeakerImageUriTest.java]: You should change method name `getSpeakerImageUri` because method name suggest it is for speaker but actually it is used for both speakers and sponsors

File: android/app/src/test/java/org/fossasia/openevent/utils/SpeakerImageUriTest.java (hunk 4 above)
Comment (Shailesh351) [inline android/app/src/test/java/org/fossasia/openevent/utils/SpeakerImageUriTest.java]: @arp95 it will not fetch image it will just test uri given to methode and returned by method.

**Comment by iamareebjamal** [comment]
Unit tests are detached from any network and other real life constraints. We can't add those considerations in them. If the images are not present. Picasso will show the error image. 

In short, it's the job of Picasso

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionSpeakerListAdapter.java (hunk 1 above)
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionSpeakerListAdapter.java]: @arp95 In most of the samples, only photo field is filled in and not the thumbnail one. And we want to show the assets one. So, if we get thumbnail to be null, then we show the photo (present in assets)

File: android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java (hunk 2 above)
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java]: If thumbnail is null, show the photo field. thumbnail is just smaller version of photo

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 Please review now

**Comment by iamareebjamal** [comment]
@arp95 Please review

**Comment by iamareebjamal** [comment]
@niranjan94 Please merge
