### PR TITLE
fix: Add new DateUtils fixing local and event dates

### LINKED ISSUE #1693: Create new DateUtils class
As with the new time response from the server, the current ISO8601 class is obsolete and buggy. Furthermore, a better and minimal class can be written which will be flexible for future changes

```Java
package org.fossasia.openevent.utils;

import android.support.annotation.VisibleForTesting;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import io.reactivex.annotations.NonNull;
import timber.log.Timber;

public class DateUtils {

    private static boolean showLocalTimeZone;

    private static final String ISO8601_WITH_TIMEZONE = "yyyy-MM-dd'T'HH:mm:ssXXX";
    private static final String ISO8601_WITHOUT_TIMEZONE = "yyyy-MM-dd'T'HH:mm:ss";

    public static void setLocalTimeZone(boolean localTimeZone) {
        showLocalTimeZone = localTimeZone;
    }

    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
    public static String getTemplateString() {
        if (showLocalTimeZone)
            return ISO8601_WITH_TIMEZONE;

        return ISO8601_WITHOUT_TIMEZONE;
    }

    @NonNull
    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
    public static Date getDate(@NonNull String isoDateString) throws ParseException {
        return new SimpleDateFormat(getTemplateString(), Locale.getDefault()).parse(isoDateString);
    }

    @NonNull
    public static String formatDate(@NonNull String format, @NonNull String isoDateString) throws ParseException {
        return new SimpleDateFormat(format, Locale.getDefault()).format(getDate(isoDateString));
    }

    @NonNull
    public static String formatDateWithDefault(@NonNull String format, @NonNull String isoString, @NonNull String defaultString) {
        String formatted = defaultString;

        try {
            formatted = formatDate(format, isoString);
        } catch (ParseException pe) {
            Timber.e(pe);
            Timber.e("Error parsing date %s with format %s and default string %s",
                    isoString,
                    format,
                    defaultString);
        }

        return formatted;
    }

}
```

This is the proposed class as of now, and working correctly for times, I'll add tests for everything

### LINKED ISSUE #1711: Unknown pattern character 'X' error in ISO8601Date
**Actual Behaviour**

Initially, the app is crashing after the downloading of data from the server. Any subsequent run of the app, the app is crashing on initialisation itself.

**Expected Behaviour**

The app should should run fine with the specified date format.

**LogCat for the issue**

screenshot from 2017-06-15 21-55-36

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 6](https://github.com/fossasia/open-event-android/milestone/29)

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1693 
Fixes #1711 

Changes: 
- Add new configurable DateUtils class, with minimal code with local and event time formatting
- Refactor code base to include DateUtils and remove ISO8601Date
- Add thorough tests

@arp95 @mahikaw @Shailesh351 @shreyasnbhat Please review

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Use https://raw.githubusercontent.com/arp95/open-event/mozilla/sample/MozillaAllHands_17 as it has several days of events

**Comment by Shailesh351** [comment]
Great work!!!   Working fine...

**Comment by shreyasnbhat** [comment]
Works fine!

**Comment by iamareebjamal** [comment]
@arp95 @mahikaw @Shailesh351 @shreyasnbhat Please review now. Refactored to increase performance a little bit

File: android/app/src/main/java/org/fossasia/openevent/utils/DateUtils.java [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+    // Need to replace dynamically for test
+    private static String iso8601WithTimezone = "yyyy-MM-dd'T'HH:mm:ssZ";
+    private static final String ISO8601_WITHOUT_TIMEZONE = "yyyy-MM-dd'T'HH:mm:ss";
+    private static final String DATE_FORMAT = "yyyy-MM-dd";
+
+    private static final String INVALID_DATE = "Invalid Date";
+    private static final Locale defaultLocale = Locale.getDefault();
+
+    // Formatters to parse date
+    private static SimpleDateFormat ISO_TIMEZONE_FORMATTER = new SimpleDateFormat(iso8601WithTimezone, defaultLocale);
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/utils/DateUtils.java]: Why to initialize here ? It will be initialized in  instantiateFormatters().

**Comment by iamareebjamal** [comment]
@arp95 @shreyasnbhat @mejariamol @mahikaw @rohanagarwal94 Please review

**Comment by iamareebjamal** [comment]
@the-dagger Please review and merge. This fixes a crashing bug on API lower than 24
