### PR TITLE
 Fixed #117 #88

### LINKED ISSUE #117: Location option in the drawer is not working in offline mode
Location is not working in the offline mode,it does not show anything on the screen.Also on changing to  offline mode after getting location data in the online mode, then refreshing cause application to get crashed.
This picture shows how it respond in the offline mode.
device-2015-12-24-222351

### PR DESCRIPTION
**Pull request by opticod**
In api/processor/*, for every success we are clearing the respective tables of database and adding new values.So, for every onRefresh(),its will clear the tables only when we have completed fetching that data else retain it.

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java [hunk 1]
```diff
@@ -165,7 +166,7 @@ public boolean onQueryTextChange(String query) {
         return true;
     }
 
-    private boolean haveNetworkConnection() {
+    public boolean haveNetworkConnection() {
```
Comment (mananwason) [inline app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java]: Why public?

File: app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java [hunk 2]
```diff
@@ -61,9 +59,7 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle sa
             @Override
             public void onRefresh() {
                 DataDownload download = new DataDownload();
-                dbSingleton.clearDatabase(DbContract.Microlocation.TABLE_NAME);
```
Comment (mananwason) [inline app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: Why have you deleted this?

File: app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java [hunk 3]
```diff
@@ -71,7 +71,6 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle sa
             public void onRefresh() {
                 if (haveNetworkConnection()) {
                     DataDownload download = new DataDownload();
-                    dbSingleton.clearDatabase(DbContract.Speakers.TABLE_NAME);
```
Comment (mananwason) [inline app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java]: Again why have you deleted this?

File: app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java (hunk 1 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java]: it may be private also.not needed

File: app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java [hunk 4]
```diff
@@ -50,7 +50,6 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle sa
             public void onRefresh() {
                 if (haveNetworkConnection()) {
                     DataDownload download = new DataDownload();
-                    dbSingleton.clearDatabase(DbContract.Sponsors.TABLE_NAME);
```
Comment (mananwason) [inline app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java]: Same here

File: app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java [hunk 5]
```diff
@@ -67,7 +67,6 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle sa
             public void onRefresh() {
                 if (haveNetworkConnection()) {
                     DataDownload download = new DataDownload();
-                    dbSingleton.clearDatabase(DbContract.Tracks.TABLE_NAME);
```
Comment (mananwason) [inline app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java]: Again

File: app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java (hunk 2 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: In api/processor/*, for every success we are clearing the respective tables of database and adding new values.So, for every onRefresh(),its will clear the tables only when we have completed fetching that data else retain it....Other wise it will show blank screen as reported in issue #117

File: app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java (hunk 1 above)
Comment (mananwason) [inline app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java]: We should try to keep private methods only. Please fix it.

File: app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java (hunk 2 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: Take the case....network is not available and u deleted the table...now so nothing to show

File: app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java (hunk 1 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java]: ok...suerly I will make it private

File: app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java (hunk 3 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java]: In api/processor/*, for every success we are clearing the respective tables of database and adding new values.So, for every onRefresh(),its will clear the tables only when we have completed fetching that data else retain it....Other wise it will show blank screen as reported in issue #117

Take the case....network is not available and u deleted the table...now so nothing to show

File: app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java (hunk 2 above)
Comment (mananwason) [inline app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: okay so where are you clearing the database. If you're not clearing it, we'll have both the new and the old values.

File: app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java (hunk 4 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java]: In api/processor/*, for every success we are clearing the respective tables of database and adding new values.So, for every onRefresh(),its will clear the tables only when we have completed fetching that data else retain it....Other wise it will show blank screen as reported in issue #117

Take the case....network is not available and u deleted the table...now so nothing to show

File: app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java (hunk 5 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java]: In api/processor/*, for every success we are clearing the respective tables of database and adding new values.So, for every onRefresh(),its will clear the tables only when we have completed fetching that data else retain it....Other wise it will show blank screen as reported in issue #117

Take the case....network is not available and u deleted the table...now so nothing to show

File: app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java (hunk 2 above)
Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: I go through the code,in api/processor files ...MicrolocationListResponseProcessor..and other files ,....after every success you are doing 
" dbSingleton.clearDatabase(DbContract.Sessions.TABLE_NAME);
                dbSingleton.insertQueries(queries);"
So,it will clear the old data and insert the new data if network allows

Comment (opticod) [inline app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: In LocationsFragment.java,when we are calling "download.downloadMicrolocations();"
it will call 
"public void downloadMicrolocations() {
        client.getOpenEventAPI().getMicrolocations(Urls.EVENT_ID, new MicrolocationListResponseProcessor());
}"
and we have defined to clear old values and insert new values @onSuccess 
" dbSingleton.clearDatabase(DbContract.Sessions.TABLE_NAME);
dbSingleton.insertQueries(queries);"

**Comment by mananwason** [comment]
Please squash. Always!!

**Comment by opticod** [comment]
@mananwason  Squashed it.Please review it.

**Comment by opticod** [comment]
@mananwason  is there any other issues with the code? 
Thank you.

**Comment by mananwason** [comment]
No @opticod Merging.
