### PR TITLE
fix: event url added in share

### LINKED ISSUE #92: Share FAB should have the url of the event
It should not contain other details just the URL of the event hosted on eventyay
Working on it

### PR DESCRIPTION
**Pull request by nikit19**
fixes #92 
screenshot_20180607-120630

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 1]
```diff
@@ -16,10 +16,12 @@ object EventUtils {
 
     private val timeFormat: DateTimeFormatter = DateTimeFormatter.ofPattern("hh:mm a")
     private val dateFormat: DateTimeFormatter = DateTimeFormatter.ofPattern("dd MMM yyyy")
+    private val frontendUrl: String = "https://open-event-frontend-dev.herokuapp.com/e/"
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: This is dev environment. Not necessary the event will be there

Comment (nikit19) [reply app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Actually in today's meeting we were asked to change it to this one. I also tested it manually for some events and the links were always working. What do you suggest should be done ?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Then it's fine
