### PR TITLE
fix: two different anims for switching between login/signup

### LINKED ISSUE #924: Two different animations for switching between Login and Signup fragment
**Describe the chore**

Two different animations appear while going from login to signup fragment
1. After opening login fragment for first time and then switching to signup fragment, the login fragment slides to right.
2. In all other cases, the switch has a fade animation

Screenshot:

issue 923

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by addiegupta**
Fixes #924 
Changes: 
Replaces slide animations with fade animations for login and signup fragments.

Screenshots for the change:
pr 932

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt [hunk 1]
```diff
@@ -137,7 +138,7 @@ class TicketsFragment : Fragment() {
         if (ticketsViewModel.isLoggedIn())
             redirectToAttendee()
         else {
-            Snackbar.make(ticketsCoordinatorLayout, "You need to log in first!", Snackbar.LENGTH_LONG).show()
+            Snackbar.make(ticketsCoordinatorLayout, getString(R.string.log_in_first), Snackbar.LENGTH_LONG).show()
```
Comment (addiegupta) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt]: Not related to the PR but makes the code cleaner
