### PR TITLE
Fixed minor UI bugs in location activity

### LINKED ISSUE #1651: Location activity UI bug
**Actual Behaviour**
Incase of no sessions in a location,

- the map of that particular location also shows up the default "no sessions" text view with the map of the location.

- On clicking back button, first the map goes, leaving just the "no sessions" text view. On clicking back button for the second time, the locations list appears.

**Expected Behaviour**

- Even if there aren't any sessions, it should simply display the map of the locations and not the "no sessions" text.

- The back button should directly lead to sessions list.

**Screenshots of the issue**

device-2017-06-04-110236

**Would you like to work on the issue?**
Yes.
**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/27

### PR DESCRIPTION
**Pull request by mahikaw**
Fixes #1651

Changes: 
When there aren't any sessions, only the map of the locations is displayed and not the "no sessions" text.

The back button directly leads to sessions list with the text "no session", as expected.

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 1]
```diff
@@ -145,6 +145,14 @@ public boolean onCreateOptionsMenu(Menu menu) {
         searchView.setQuery(searchText, false);
         return true;
     }
+    @Override
+    public void onBackPressed(){
+        if((mSessions.isEmpty())&&(sessionRecyclerView.getVisibility()==View.GONE)){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Is checking the sessionRecyclerView's visibility necessary here. If we include this check here, then we are depending on other variable whose state may give us different results making the code buggy

Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: In this case, if the recycler view is visible, then there is no point for the back button. The back button is to reach the session list activity for that microlocation. Similar coding has been done previously too.

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: The problem is that the visibility of recyclerview is in our hand. If someone forgets to hide or show it, this conditional will give different results

Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: could you suggest a workaround for it in that case. I can't really think of anything else. Also, we might want to change the existing code and remove such conditions in that case?

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: I'll get back to you after testing this

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @mahikaw I'm testing this currently, can you tell me the specific use case for a particular location where this condition will be needed?

Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Yes, when on the map fragment, if we press backbitten and there are no sessions, the recycler view doesn't appear, but what the current code doesn't do is to make the no sessions text view visible. I have tried to address that here.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 2]
```diff
@@ -145,6 +145,14 @@ public boolean onCreateOptionsMenu(Menu menu) {
...
+            noSessionsView.setVisibility(View.VISIBLE);
```
Comment (mejariamol) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: What happens when user presses back button second time once `noSessionsView` is set visible?

Comment (mejariamol) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: What happens when user presses back button second time once `noSessionsView` is visible?

Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: then it skips this onbackpressed() and instead the super.onbackpressed() is called which leads to locations list as expected.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 1 above)
Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @iamareebjamal is this PR sorted now?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 2 above)
Comment (mejariamol) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: For that to happen there should be `noSessionsView` visibility check in the case right?

Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: I don't think so. I tested it and it was working just fine. Could you confirm @mejariamol

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 1 above)
Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @iamareebjamal any updates regarding this?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 2 above)
Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @mejariamol it works fine in that case.

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @mahikaw Sorry for late reply. I tried just using `mSessions.isEmpty()`, and it worked for most use cases. Can you confirm a use case where it won't, because if it is so, this too is a bug

Because `sessionRecyclerView` should always be `View.GONE` when `mSessions.isEmpty()`

**Comment by mahikaw** [comment]
@iamareebjamal Did you have a chance to check this?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 2 above)
Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Yes, you are right @iamareebjamal I am updating it.

**Comment by mahikaw** [comment]
@iamareebjamal Please review and merge.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 3]
```diff
@@ -145,6 +145,14 @@ public boolean onCreateOptionsMenu(Menu menu) {
         searchView.setQuery(searchText, false);
         return true;
     }
+    @Override
+    public void onBackPressed(){
+        if((mSessions.isEmpty())){
+            noSessionsView.setVisibility(View.VISIBLE);
+        }
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @mahikaw here if mSessions is not empty then recycler view should be visible.

Comment (mahikaw) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Yes, @Shailesh351 It is visible. This is being handled by the super.onbackpressed()
