### PR TITLE
fix: Handle configuration changes for MainActivity

### LINKED ISSUE #744: Event fragment is set during selecting the search parameter
**Describe the bug**
Search perform in events after entering a location in the search section

**To Reproduce**
1. Go to the search section
2. Try to enter a location
3. Event fragment is open instead of changing the location

**Screenshots**
<p align="center">
 
</p>

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Mi Max 2|
|Android Version|Nougat 7.1|

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #744 #738

### CODE REVIEW

**Comment by liveHarshit** [comment]
Changes in PR #739 contains bugs because, in many places, Flag activity clear top is used. In that case, while intent to the main activity

if (savedInstanceState == null) {
            loadFragment(supportFragmentManager, EventsFragment(), frameContainer.id)
        }

        else
Only if statement is executed and all arguments are not used.

**Comment by liveHarshit** [comment]
When device orientation is changed, activity receives the previous bundle, due to this Ticket fragment is set on rotation if authentication done by ticket fragment.

Here I set null value to the bundle if the orientation is changed, otherwise accept bundle from the intent.

**Comment by liveHarshit** [comment]
@iamareebjamal @nikit19 Please review.

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 1]
```diff
@@ -69,30 +69,24 @@ class MainActivity : AppCompatActivity() {
 
         supportActionBar?.title = "Events"
 
-        val bundle = intent.extras
+        val bundle = if (savedInstanceState == null) intent.extras else null
 
-        if (savedInstanceState == null) {
-            loadFragment(supportFragmentManager, EventsFragment(), frameContainer.id)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: How does the new code handle this case?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: How does this case is used?, I don't understand. Because both issues are resolved with set bundle to null when orientation changed.

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 2]
```diff
@@ -69,30 +69,24 @@ class MainActivity : AppCompatActivity() {
...
 
-            if (bundle != null && (bundle.getBoolean(TICKETS) || bundle.getBoolean(LAUNCH_TICKETS))) {
-                loadFragment(supportFragmentManager, OrdersUnderUserFragment(), frameContainer.id)
-                supportActionBar?.title = "Tickets"
-                navigation.selectedItemId = R.id.navigation_tickets
-            }
+        if (bundle != null && (bundle.getBoolean(TICKETS) || bundle.getBoolean(LAUNCH_TICKETS))) {
+            loadFragment(supportFragmentManager, OrdersUnderUserFragment(), frameContainer.id)
+            supportActionBar?.title = "Tickets"
+            navigation.selectedItemId = R.id.navigation_tickets
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: MOove all 3 cases in a block

```
if (bundle != null) {
   ...
}
```

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Updated
