### PR TITLE
fix: remove post handlers

### LINKED ISSUE #830: Remove post handlers used to show snackbars
**Describe the bug**

Remove post handlers and show snackbar in target activities/fragment

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### LINKED ISSUE #840: App crashes due to snackbar text
**Describe the bug**
App crashes while opening another fragment during snack bar handler is running.

**To Reproduce**
1. Log out
2. Click on profile
3. Now instantly click on tickets within a second

**Logs**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 2674
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.content.ComponentName.<init>(ComponentName.java:128)
        at android.content.Intent.<init>(Intent.java:4910)
        at org.fossasia.openevent.general.auth.ProfileFragment.redirectToLogin(ProfileFragment.kt:44)
```

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Mi Max 2|
|Android Version|Nougat 7.1|

**Would you like to work on the issue?**

Has PR #838

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Fixes #830 
fixes #840 

### Description
Remove posthandler that are defering the transition and improve the logic to show snackbar

GIF for the change:

#### Signup

gif-190105_121407

#### login
ezgif com-video-to-gif 1

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt [hunk 1]
```diff
@@ -68,4 +72,13 @@ class AuthActivity : AppCompatActivity() {
         super.onBackPressed()
         startActivity(Intent(this, MainActivity::class.java).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP))
     }
+
+    private fun snackbar() {
+        showSnackbar = intent.getBooleanExtra("showSnackbar", false)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt]: Pass a string instead of boolean

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 2]
```diff
@@ -54,4 +59,13 @@ class MainActivity : AppCompatActivity() {
                 else -> View.GONE
         }
     }
+
+    private fun snackbar() {
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: It would be better if the function name was more meaningful

Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: is 'isSnackbar' fine? 😅

File: app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt [hunk 3]
```diff
@@ -68,4 +74,13 @@ class AuthActivity : AppCompatActivity() {
         super.onBackPressed()
         startActivity(Intent(this, MainActivity::class.java).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP))
     }
+
+    private fun isSnackbar() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt]: isSnackbar should return a boolean and tell if this activity is a snackbar with no side effects

File: app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt [hunk 4]
```diff
@@ -68,4 +74,13 @@ class AuthActivity : AppCompatActivity() {
...
+        showSnackbar = intent.getStringExtra("showSnackbar")?:"false"
+        if (showSnackbar == "true") {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt]: That might be a first for me in 6 years. May I ask why this brilliant idea? /s

I asked you to pass the string to be shown in snackbar, not write "true" and "false" like booleans don't exist in the language. Try to understand why reviewers ask changes, and think how is this better from what was there before. Spoiler Alert: It is not

Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt]: Indeed I think the same way when writing above code

> Pass a string instead of boolean

I misinterpret above statement, will fix soon

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal  pls review

File: app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt [hunk 5]
```diff
@@ -166,4 +153,16 @@ class ProfileFragment : Fragment() {
         setHasOptionsMenu(true)
         super.onResume()
     }
+
+    private fun redirectToLogin() {
+        val intent = Intent(activity, AuthActivity::class.java)
+        intent.putExtra("isSnackbar", true)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: Unneeded

File: app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt [hunk 6]
```diff
@@ -111,6 +105,8 @@ class SignUpFragment : Fragment() {
 
     private fun redirectToMain() {
         val intent = Intent(activity, MainActivity::class.java)
+        intent.putExtra("isSnackbar", true)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Unneeded

Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: I put this line to check whether the mainActivity is called from signupfragment and only in that  case show snackbar in mainActivity but if I remove this and also the check present in mainActivity  snackbar will be displayed every time we visit mainActivity. Pls correct

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Why though? It will only be displayed if the string to be displayed is passed in

**Comment by GOVINDDIXIT** [comment]
@nikit19 pls review

File: app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt [hunk 7]
```diff
@@ -166,4 +153,15 @@ class ProfileFragment : Fragment() {
         setHasOptionsMenu(true)
         super.onResume()
     }
+
+    private fun redirectToLogin() {
+        val intent = Intent(activity, AuthActivity::class.java)
+        intent.putExtra("textSnackbar", "You need to log in first!")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: Change intent extra name to `snackbar_message` and make it a constant

Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: > make it a constant

means I have to store and extract the strings

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: Yes

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal can you please guide me in these conflicts, we are showing snackbar on activity change but with current config we are moving towards single activity app

**Comment by iamareebjamal** [comment]
So, what's the issue?

**Comment by iamareebjamal** [comment]
The same can be done with fragments

**Comment by GOVINDDIXIT** [comment]
Yes, just informing 😅, will push changes soon

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 8]
```diff
@@ -74,4 +77,12 @@ class MainActivity : AppCompatActivity() {
             else -> super.onBackPressed()
         }
     }
+
+    private fun showSnackbar() {
+        val textSnackbar = intent.getStringExtra("snackbar_message")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Extract to a constant string "snackbar_message"

Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: I have to change textSnackbar to snackbar_message ?

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 9]
```diff
@@ -146,4 +147,10 @@ class LoginFragment : Fragment() {
             else -> super.onOptionsItemSelected(item)
         }
     }
+
+    private fun showSnackbar() {
+        Snackbar.make(
+            rootView.loginCoordinatorLayout, getString(R.string.log_in_first), Snackbar.LENGTH_SHORT
+        ).show()
+    }
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Why is this showed unconditionally?

File: app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt [hunk 10]
```diff
@@ -130,7 +126,11 @@ class SignUpFragment : Fragment() {
     }
 
     private fun redirectToMain() {
-        findNavController(rootView).popBackStack()
+        val intent = Intent(activity, MainActivity::class.java)
+        intent.putExtra("snackbar_message", getString(R.string.logged_in_automatically))
+        startActivity(intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP))
+        activity?.overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right)
+        activity?.finish()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Revert please. We are now single activity application

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 9 above)
Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: I think there is no need of a check as showing snackbar whenever one need to login is apt. Pls correct me

File: app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt (hunk 10 above)
Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Pls suggest alternate way I'm new to navigation architecture

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 9 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: No, if someone goes to login him/herself. There is no need of showing snackbar

File: app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt (hunk 10 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Read about it

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 9 above)
Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: currently login fragment loads whenever one go for profile or tickets without being logged in and then snackbar is shown

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal  pls review

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 11]
```diff
@@ -146,4 +147,13 @@ class LoginFragment : Fragment() {
             else -> super.onOptionsItemSelected(item)
         }
     }
+
+    private fun showSnackbar() {
+        val textSnackbar = arguments?.getString("snackbar_message")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Where is this used below?

Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: I only used this to check whether snackbar should be showed or not in login fragment.

File: app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt [hunk 12]
```diff
@@ -42,13 +42,22 @@ class ProfileFragment : Fragment() {
     private val EMAIL: String = "EMAIL"
 
     private fun redirectToLogin() {
-        findNavController(rootView).navigate(R.id.loginFragment, null, getAnimSlide())
+        val args = getString(R.string.log_in_first)
+        val bundle = bundleOf("snackbar_message" to args)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: No use of the constant unless it is used everywhere

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: Try to understand the reason why the changes are requested rather than blindly making them

File: app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt [hunk 13]
```diff
@@ -29,6 +29,7 @@ import timber.log.Timber
 
 const val ORDERS: String = "orders"
 const val LAUNCH_TICKETS: String = "LAUNCH_TICKETS"
+const val SNACKBAR_MESSAGE: String = "SNACKBAR_MESSAGE"
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt]: We need to remove duplication. What's the use of refactoring to a constant if you are going to write it in every file it is used
