### PR TITLE
fix: Unnecessary calls for social links and similar events

### LINKED ISSUE #1509: Unnecessary calls for social links and similar events
**Describe the bug**
There are unnecessary calls for social links and similar events when the user comes back to the event details page

**Expected behavior**
Should be call once.

**Screenshots**

**Would you like to work on the issue?**
- Yes

### PR DESCRIPTION
**Pull request by aman210697**
Fixes #1509
Changes: Move API calls from onCreateView to onCreate

Screenshots for the change:

### CODE REVIEW

**Comment by aman210697** [comment]
@liveHarshit @yashk2000 please review.

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt [hunk 1]
```diff
@@ -19,6 +19,7 @@ class SocialLinksViewModel(private val socialLinksService: SocialLinksService) :
     val socialLinks: LiveData<List<SocialLink>> = mutableSocialLinks
     private val mutableError = SingleLiveEvent<String>()
     val error: LiveData<String> = mutableError
+    val mutableInternetError: MutableLiveData<Boolean> = MutableLiveData<Boolean>()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: This isn't used anywhere

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: I have used it in SocialLinksFragment.kt: 105 & 107

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: But you are not posting any value from the VM

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: SocialLinksFragment.kt: 83
To show no internet layout.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: LiveData should only be mutated from VM

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: Oh ok. I should make set fun for it?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: No, check connection stuff from the VM itself

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: done..

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt [hunk 2]
```diff
@@ -80,7 +80,15 @@ class SocialLinksFragment : Fragment() {
                 Snackbar.make(socialLinksCoordinatorLayout, it, Snackbar.LENGTH_LONG).show()
             })
 
-        loadSocialLink()
+        socialLinksViewModel.mutableInternetError
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt]: Subscribe to `internetError`, make `mutableInternetError` private

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt [hunk 3]
```diff
@@ -1,5 +1,6 @@
 package org.fossasia.openevent.general.social
 
+import android.content.Context
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: There should be no imports of android.* in ViewModel

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt (hunk 2 above)
Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt]: Sure, what's the benefit btw?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt]: So that contributors don't make the mistake of posting values from fragments and activities

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt (hunk 3 above)
Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: how can I use context then?

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt (hunk 2 above)
Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt]: Oh Okay..

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt (hunk 3 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: You can't. That's the point of ViewModel. Each time a programmer uses context or view reference in ViewModel, MVVM dies a thousand deaths and rolls in its grave

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: lol, so what's the solution?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: See how strings are getting loaded in the ViewModel

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt (hunk 2 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt]: MVVM View and ViewModel don't have a bidirectional relationship. VM posts and view listens. View only interacts with VM by asking for things. It never provides something to VM

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt (hunk 3 above)
Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: through injection?

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: Did it just like the resource

File: app/src/main/java/org/fossasia/openevent/general/data/AppContext.kt [hunk 4]
```diff
@@ -0,0 +1,12 @@
+package org.fossasia.openevent.general.data
+
+import org.fossasia.openevent.general.OpenEventGeneral
+
+class AppContext {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/data/AppContext.kt]: This is not how Resource works at all

**Comment by aman210697** [comment]
> To be honest, I don't think that you have even taken a look at the project
> 
> [/app/src/main/java/org/fossasia/openevent/general/data/Network.kt@`development`](https://github.com/fossasia/open-event-android/blob/development/app/src/main/java/org/fossasia/openevent/general/data/Network.kt)

I'm still learning this DI part. ^^

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt [hunk 5]
```diff
@@ -80,7 +80,15 @@ class SocialLinksFragment : Fragment() {
                 Snackbar.make(socialLinksCoordinatorLayout, it, Snackbar.LENGTH_LONG).show()
             })
 
-        loadSocialLink()
+        socialLinksViewModel.internetError
+            .nonNull()
+            .observe(viewLifecycleOwner, Observer {
+                if (it) {
+                    rootView.socialNoInternet.visibility = View.VISIBLE
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt]: rootView.socialNoInternet.isVisible = it

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt]: done..
