### PR TITLE
fix: Added Confirmation Dialog

### LINKED ISSUE #1342: Add Confirmation Dialog
**Describe the chore**
User should be notified of the order before the order is placed.
Alert Dialog may be used for this.
It is a common practice.
**Would you like to work on the issue?**

- [x] Yes

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #1342 

Changes: Before completion of order, an Alert Dialog is displayed to check it's confirmation.

Screenshots for the change:

ezgif com-video-to-gif

### CODE REVIEW

**Comment by somenath1435** [comment]
@iamareebjamal please review

**Comment by aggarwalpulkit596** [comment]
fix the Travis error 

 Errors found:
  
  /home/travis/build/fossasia/open-event-android/app/src/main/res/values/strings.xml:198: Error: "confirmation_dialog" is not translated in "vi" (Vietnamese) or "bn" (Bengali) [MissingTranslation]
      <string name="confirmation_dialog">Are you sure to confirm the order?</string>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/travis/build/fossasia/open-event-android/app/src/main/res/values/strings.xml:199: Error: "order_not_completed" is not translated in "vi" (Vietnamese) or "bn" (Bengali) [MissingTranslation]
      <string name="order_not_completed">Order not completed!</string>

**Comment by somenath1435** [comment]
@nikit19 Can you please tell why build is failing?

**Comment by ShridharGoel** [comment]
Check out #1324 to know the reason of failing build, which is due to missing translations.

**Comment by somenath1435** [comment]
@iamareebjamal @nikit19 Travix build ok now

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 1]
```diff
@@ -245,8 +245,9 @@ class AttendeeFragment : Fragment() {
                         else -> 0
                     }
                 }
-                    setCardSelectorAndError(pos, visibility = false, error = false)
+                setCardSelectorAndError(pos, visibility = false, error = false)
             }
+
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Unrelated changes.

Comment (somenath1435) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: @liveHarshit Removed extra space

**Comment by somenath1435** [comment]
@iamareebjamal please review

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 2]
```diff
@@ -245,7 +245,7 @@ class AttendeeFragment : Fragment() {
                         else -> 0
                     }
                 }
-                    setCardSelectorAndError(pos, visibility = false, error = false)
+                setCardSelectorAndError(pos, visibility = false, error = false)
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Why these changes?

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 3]
```diff
@@ -427,43 +427,53 @@ class AttendeeFragment : Fragment() {
...
-                    address = getAttendeeField("address"),
-                    state = getAttendeeField("state"),
-                    email = email.text.toString(),
-                    ticket = TicketId(ticket),
-                    event = eventId)
-                attendees.add(attendee)
-            } else {
-                attendees.addAll(attendeeRecyclerAdapter.attendeeList)
+
+            val builder = AlertDialog.Builder(rootView.context)
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Use `requireContext()` instead of `rootView.context`

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt (hunk 2 above)
Comment (somenath1435) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: This is autoformatted by android studio

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt (hunk 3 above)
Comment (somenath1435) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Will do soon

Comment (somenath1435) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: @liveHarshit Done

**Comment by somenath1435** [comment]
@iamareebjamal please review .
Resolved conflicts
