### PR TITLE
fix: Make name field editable in Attendee fragment

### LINKED ISSUE #1970: Make first and last name field editable in ticket registration form
**Describe the bug**
Make the first and last name field editable if the user name is not registered with the profile.

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1970 
<p align="center">
 
</p>

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 1]
```diff
@@ -812,8 +819,8 @@ class AttendeeFragment : Fragment(), ComplexBackPressFragment {
         rootView.firstName.text = SpannableStringBuilder(user.firstName.nullToEmpty())
         rootView.lastName.text = SpannableStringBuilder(user.lastName.nullToEmpty())
         rootView.email.text = SpannableStringBuilder(user.email.nullToEmpty())
-        rootView.firstName.isEnabled = false
-        rootView.lastName.isEnabled = false
+        rootView.firstName.isEnabled = user.firstName.isNullOrEmpty()
+        rootView.lastName.isEnabled = user.firstName.isNullOrEmpty()
```
Comment (ShridharGoel) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Should be `user.lastName.isNullOrEmpty()`
