### PR TITLE
fix: making search in EventsFragment works again

### LINKED ISSUE #1349: Search doesn't work in EventsFragment
**Describe the bug**
Needs to reload in order for searching in EventsFragment works. This is due to my PR #1296, I know the cause of the problem so I will fix it

**Screenshots**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anhanh11001**
**Details:**
Add a String to store the last search so that if a new search come, it reloads events again
Fixes #1349

**Screenshots for the change:**
Search works again, doesn't need to swipe down to reload

When rotating screen, the events are still retained

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt [hunk 1]
```diff
@@ -24,6 +24,7 @@ class EventsViewModel(private val eventService: EventService, private val prefer
     val error: LiveData<String> = mutableError
     private val mutableShowShimmerEvents = MutableLiveData<Boolean>()
     val showShimmerEvents: LiveData<Boolean> = mutableShowShimmerEvents
+    private val mutableLastSearch = MutableLiveData<String>()
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Why mutable String? Can't you use a simple String instead?

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: You are right, it still works fine with String so I'm sending a new commit now

File: app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt [hunk 2]
```diff
@@ -24,6 +24,7 @@ class EventsViewModel(private val eventService: EventService, private val prefer
     val error: LiveData<String> = mutableError
     private val mutableShowShimmerEvents = MutableLiveData<Boolean>()
     val showShimmerEvents: LiveData<Boolean> = mutableShowShimmerEvents
+    private var lastSearch = String()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt]: Just use  ""
