### PR TITLE
fix: not showing sessions in draft state

### LINKED ISSUE #1681: Not showing sessions which have draft state
**Actual Behaviour**

Currently we are showing all sessions without loooking at their state.

**Expected Behaviour**

Not show sessions with "state": "draft"

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/29

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1681

Changes: 
Not showing sessions in draft state.

Screenshots for the change: 

-

### CODE REVIEW

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 @mahikaw
please review.

File: android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java [hunk 1]
```diff
@@ -93,6 +93,14 @@ protected void onCreate(Bundle savedInstanceState) {
         sessionsRecyclerView.setHasFixedSize(true);
         gridLayoutManager = new GridLayoutManager(this, spanCount);
         sessionsRecyclerView.setLayoutManager(gridLayoutManager);
+
+        //removing sessions with draft state
+        for(int i=0; i<mSessions.size(); i++) {
+            if(mSessions.get(i).getState().equals("draft")) {
+                mSessions.remove(i);
+            }
+        }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java]: This won't handle when the sessions are updated through Realm, and you are removing when the list is empty since the data is not necessarily loaded

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java]: Do this in `onBindViewHolder`

```Java
items.remove(position);
notifyItemRemoved(position);
```

**Comment by arp95** [comment]
@iamareebjamal 
this is the way you are talking about?
also the last one was also working, but yeah dont know incase of no sessions.

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java [hunk 2]
```diff
@@ -125,6 +125,12 @@ public SessionViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
     @Override
     public void onBindViewHolder(final SessionViewHolder holder, final int position) {
         Session session = getItem(position);
+
+        //removing session when in draft state
+        if(session.getState().equals("draft")) {
+            notifyItemRemoved(position);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: Also remove the item from the list

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java [hunk 3]
```diff
@@ -125,6 +125,12 @@ public SessionViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
     @Override
     public void onBindViewHolder(final SessionViewHolder holder, final int position) {
         Session session = getItem(position);
+
+        //removing session when in draft state
+        if(session.getState().equals("draft")) {
+            removeItem(session);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: The function in super class is extremely inefficient. When you have the position, directly call, remove(position) and notifyItemRemoved(position)

Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: remove() is not recognised. should i create a list variable while initializing and then use that?

Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: actually i cant find any way accessing list object form here. i have to the BaseRVAdapter class anyway.

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: getData() should do it?

Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: nope. again not found.
can you please check and tell the problem because accessing  the list object over here doesnt seem possible to me.

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: You can either implement getData or removeItem(position) in BaseRvAdapter

Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: also the removeItem(item) runs very slow. it has a time complexity of O(n) which can be easily removed to a constant one. i think you were referring to this thing before.

**Comment by arp95** [comment]
@iamareebjamal please review.

**Comment by mariobehling** [comment]
@iamareebjamal Please only merge after two other contributors have approved this pull request.
