### PR TITLE
fix: issue Sort Sponsors according to sponsorship level

### LINKED ISSUE #1280: Sort Sponsors according to sponsorship level
Sponsors are currently not sorted to their level. Please ensure the sponsors are listed according to the order. In the server app it is sorted according to numbers, e.g. 5 is higher than -2. So the sponsor is on top. If two sponsors have the number 5 there are both in the same category.

### PR DESCRIPTION
**Pull request by Jonsnow21**
Fixes #1280 

Changes: Changed the sort order to descending

Screenshots for the change: 
screenshot_2017-03-12-19-24-33_org fossasia openevent

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java [hunk 1]
```diff
@@ -26,7 +26,7 @@
     public static final String TAG = DatabaseOperations.class.getSimpleName();
     private static final String ASCENDING = " ASC";
 
-//    private static final String DESCENDING = " DESC";
+    private static final String DESCENDING = " DESC";
```
Comment (harshitagupta30) [inline android/app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java]: Can you please reformat this line? :+1:

**Comment by mariobehling** [comment]
Good job. Thanks.
