### PR TITLE
fix: infinite progress bar bug

### LINKED ISSUE #130: ticket progress bar is visible even after loading ticket
working on it 👍

### PR DESCRIPTION
**Pull request by simarsingh24**
fixes #130

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt [hunk 1]
```diff
@@ -25,6 +25,7 @@ class SocialLinksViewModel(private val socialLinksService: SocialLinksService) :
                     progress.value = false
                 }).subscribe({
                     socialLinks.value = it
+                    progress.value = false
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt]: Remove the `progress.value = false` above this one

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt [hunk 2]
```diff
@@ -28,6 +28,7 @@ class TicketsViewModel(private val ticketService: TicketService) : ViewModel() {
                     progressTickets.value = false
                 }).subscribe({ticketList ->
                     tickets.value = ticketList
+                    progressTickets.value = false
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt]: Same here
