### PR TITLE
fix: crash on sign up

### LINKED ISSUE #1920: App is freezing on auth fragment
**Describe the bug**
The app is freezing on auth fragment in API 28
- Due to google smart authentication

### PR DESCRIPTION
**Pull request by anhanh11001**
Details:
- Move hint from TextInputEditText to TextInputLayout due to an Android bug that create a crash
- Add check so that when clicking on Google Auth in LoginFragment, it doesn't redirect back to AuthFragment

Related issue:
https://stackoverflow.com/questions/45898228/android-attempt-to-invoke-virtual-method-void-android-view-view-getboundsonsc

Fixes: #1923 
Fixes #1920

### CODE REVIEW

**Comment by liveHarshit** [comment]
Wrong issue mentioned!

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 1]
```diff
@@ -124,14 +124,13 @@ class LoginFragment : Fragment() {
 
         rootView.email.addTextChangedListener(object : TextWatcher {
             override fun afterTextChanged(s: Editable) {
-                findNavController(rootView).navigate(LoginFragmentDirections
-                    .actionLoginToAuthPop(redirectedFrom = safeArgs.redirectedFrom, email = s.toString()))
+                if (s.toString() != safeArgs.email)
+                    findNavController(rootView).navigate(LoginFragmentDirections
+                        .actionLoginToAuthPop(redirectedFrom = safeArgs.redirectedFrom, email = s.toString()))
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]:
```java
 if (BuildConfig.FLAVOR == PLAY_STORE_BUILD_FLAVOR) {

            smartAuthViewModel.requestCredentials(SmartAuthUtil.getCredentialsClient(requireActivity()))

            smartAuthViewModel.id
                .nonNull()
                .observe(viewLifecycleOwner, Observer {
                    email.text = SpannableStringBuilder(it)
                })

            smartAuthViewModel.password
                .nonNull()
                .observe(viewLifecycleOwner, Observer {
                    password.text = SpannableStringBuilder(it)
                })

            smartAuthViewModel.apiExceptionCodePair.nonNull().observe(viewLifecycleOwner, Observer {
                SmartAuthUtil.handleResolvableApiException(
                    it.first, requireActivity(), it.second)
            })

            smartAuthViewModel.progress
                .nonNull()
                .observe(viewLifecycleOwner, Observer {
                    progressDialog.show(it)
                })
        }
```
Here it fails.

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: I think a workaround is to move this block of code 
```
 rootView.email.addTextChangedListener(object : TextWatcher {
            override fun afterTextChanged(s: Editable) {
 if (s.toString() != safeArgs.email)
                    findNavController(rootView).navigate(LoginFragmentDirections
                        .actionLoginToAuthPop(redirectedFrom = safeArgs.redirectedFrom, email = s.toString()))
   override fun beforeTextChanged(s: CharSequence, start: Int, count: Int, after: Int) { /*Do Nothing*/ }
            override fun onTextChanged(email: CharSequence, start: Int, before: Int, count: Int) { /*Do Nothing*/ }
        })
```
into here

```
if (safeArgs.email.isNotEmpty()) {
            rootView.email.text = SpannableStringBuilder(safeArgs.email)
        // HERE <------------------------
} else if (BuildConfig.FLAVOR == PLAY_STORE_BUILD_FLAVOR) {

            smartAuthViewModel.requestCredentials(SmartAuthUtil.getCredentialsClient(requireActivity()))

            smartAuthViewModel.id
                .nonNull()
                .observe(viewLifecycleOwner, Observer {
                    email.text = SpannableStringBuilder(it)
                    Timber.d("DEBUGGING ${email.text.toString()}")
                })

            smartAuthViewModel.password
                .nonNull()
                .observe(viewLifecycleOwner, Observer {
                    password.text = SpannableStringBuilder(it)
                })

            smartAuthViewModel.apiExceptionCodePair.nonNull().observe(viewLifecycleOwner, Observer {
                SmartAuthUtil.handleResolvableApiException(
                    it.first, requireActivity(), it.second)
            })

            smartAuthViewModel.progress
                .nonNull()
                .observe(viewLifecycleOwner, Observer {
                    progressDialog.show(it)
                })
        }
```

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Good idea. Do the changes and will test if both bugs will fix.

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: I have pushed a new update, can you test it as I'm still struggling to set up the environment

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Sure

**Comment by liveHarshit** [comment]
Both solved. One little bug is there with smart auth, will solve that later. :+1:

**Comment by iamareebjamal** [comment]
Writing Fixes and multiple issues on same line does not work

**Comment by iamareebjamal** [comment]
@anhanh11001 Your commit closed #1922
