### PR TITLE
fix: Revalidate profile from API

### LINKED ISSUE #1904: Fetch profile from API and revalidate from database
Add refresh button to retrieve user information from the server instead of the database.
Whenever profile information updated from server side it will not retrieve in the app.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1904

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt [hunk 1]
```diff
@@ -76,6 +76,14 @@ class AuthService(
                 }
     }
 
+    fun updateProfile(id: Long = authHolder.getId()): Single<User> {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: Where is it updating the profile?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: Inserting in the database and updating in the profile fragment without showing progress.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: That's fetching/saving/syncing

Updating is if you sent come data on server to update/

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: Not getting it. Mean retrieving information from the server and updating the same on the server.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: > come data

Data coming from API?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: Updated

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: But here we are updating User name only in edit profile fragment which is already updating on server. And now syncing the data is required because profile verification is working from the server side.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: Why is the name of method updateProfile?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: Oh got it. It shouldn't. It can be sync or fetch profile.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt]: Updated
