### PR TITLE
fix: loading of SpeakerImage in SpeakerDetailsActivity resolved

### LINKED ISSUE #1277: Bug in SpeakersDetailActivity
**Actual Behaviour**

Currently when the internet is switched off and switched on again the speaker image in the speakersDetailActivity doesnt get updated.

**Expected Behaviour**

Enabling speaker image to be loaded into the speaker image view.

**Steps to reproduce it**

1. Switch off your internet
2. Move to the SpeakersDetailActivity
3. Switch on your internet now.
4. Now the speaker image should have loaded but isn't happening like this.

**LogCat for the issue**

-

**Screenshots of the issue**

Without internet

17200796_10210693782535184_219987600_o

With internet

17200282_10210693782495183_552954556_o

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1277 

Changes: 
Added a network listener to listen for network change and consequently display speaker image when user changes the network settings.

Screenshots for the change: 

17237184_10210723772084904_1968310279_o

17310798_10210723774924975_586314479_o

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/utils/NetworkStateReceiver.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+import android.net.NetworkInfo;
+
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * Created by arpitdec5 on 13-03-2017.
+ */
+
+public class NetworkStateReceiver extends BroadcastReceiver {
```
Comment (harshitagupta30) [inline android/app/src/main/java/org/fossasia/openevent/utils/NetworkStateReceiver.java]: Hi @arp95! Could you please reformat the entire code? Thanks :+1:

Comment (arp95) [inline android/app/src/main/java/org/fossasia/openevent/utils/NetworkStateReceiver.java]: @harshitagupta30
i think there is no need. And its better the mentors have a look at it and review.

Comment (the-dagger) [inline android/app/src/main/java/org/fossasia/openevent/utils/NetworkStateReceiver.java]: @arp95 We already have NetworkUtils to use that instead of creating a new java class for this.

**Comment by arp95** [comment]
@the-dagger 
please review now.
