### PR TITLE
fix : App crash while trying to editing a profile with no profile picture

### LINKED ISSUE #683: APP CRASH : Edit Profile is crashing the app
After logging in and navigating to the profile section, clicking on Edit Profile from the menu bar, the app crashes.
EDIT : Only happens with profiles with no profile picture. A user having a profile picture will face no issue

**To Reproduce**
1. Login / Sign Up 
2. Navigate to Profile Tab
3. Open Menu Bar (3 Dots)
4. Choose Edit Profile

**Expected behavior**
Edit Profile fragment must open up normally

**Logs**
LOGCAT -
`2018-11-03 19:39:58.330 17737-17737/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 17737
    java.lang.IllegalArgumentException: Path must not be empty.
        at com.squareup.picasso.Picasso.load(Picasso.java:332)
        at org.fossasia.openevent.general.auth.EditProfileFragment$onCreateView$1.onChanged(EditProfileFragment.kt:62)
        at org.fossasia.openevent.general.auth.EditProfileFragment$onCreateView$1.onChanged(EditProfileFragment.kt:33)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at org.fossasia.openevent.general.auth.ProfileFragmentViewModel$fetchProfile$3.accept(ProfileFragmentViewModel.kt:41)
        at org.fossasia.openevent.general.auth.ProfileFragmentViewModel$fetchProfile$3.accept(ProfileFragmentViewModel.kt:10)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
        at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onSuccess(SingleDoFinally.java:73)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSuccess(SingleDoOnSubscribe.java:77)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)`

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device        | Moto G4 |
|Android Version| Nougat 7.0 |

**Would you like to work on the issue?**

 Yes

### PR DESCRIPTION
**Pull request by trancenoid**
Fixes #683 

Changes: Added code to check if the profile picture URL is not empty, as Picasso requires a non-empty url. Thus if there is no profile picture initially, there should be no attempt to load such an image.

### CODE REVIEW

**Comment by trancenoid** [comment]
@iamareebjamal Would you please review my PR?

File: app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt [hunk 1]
```diff
@@ -58,11 +58,14 @@ class EditProfileFragment : Fragment() {
                 context?.let { ctx ->
                     val drawable = AppCompatResources.getDrawable(ctx, R.drawable.ic_account_circle_grey_24dp)
                     drawable?.let { icon ->
-                        Picasso.get()
-                            .load(imageUrl)
-                            .placeholder(icon)
-                            .transform(CircleTransform())
-                            .into(rootView.profilePhoto)
+                        if(!imageUrl.equals("")) { // picasso requires the imageUrl to be non empty
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: Use TextUtils.isEmpty

**Comment by iamareebjamal** [comment]
Follow commit message guidelines

File: app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt [hunk 2]
```diff
@@ -58,7 +58,7 @@ class EditProfileFragment : Fragment() {
                 context?.let { ctx ->
                     val drawable = AppCompatResources.getDrawable(ctx, R.drawable.ic_account_circle_grey_24dp)
                     drawable?.let { icon ->
-                        if(!imageUrl.equals("")) { // picasso requires the imageUrl to be non empty
+                        if(!imageUrl.isEmpty()) { // picasso requires the imageUrl to be non empty
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: It'll fail on null

Comment (trancenoid) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]:
```suggestion
                val userFirstName = it.firstName.nullToEmpty()
                val userLastName = it.lastName.nullToEmpty()
                val imageUrl = it.avatarUrl.nullToEmpty()
                rootView.firstName.setText(userFirstName)
                rootView.lastName.setText(userLastName)
                context?.let { ctx ->
                    val drawable = AppCompatResources.getDrawable(ctx,   drawable.ic_account_circle_grey_24dp)
                    drawable?.let { icon ->
                        if(!imageUrl.isEmpty()) { // picasso requires the imageUrl to be non empty
                            Picasso.get()
                                         .load(imageUrl).....
```
I think ` val imageUrl = it.avatarUrl.nullToEmpty()` will take care of that

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: OK. So, we can add the if statement even above the `context.let`

**Comment by iamareebjamal** [comment]
> Updated, but I think I made another commit which is not advises as per the rules, I dont really know the procedure to amend a commit from a forked repo

Just update the PR title

File: app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt (hunk 2 above)
Comment (trancenoid) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: Sure, I will do it

Comment (trancenoid) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: @iamareebjamal Done

File: app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt [hunk 3]
```diff
@@ -55,14 +55,17 @@ class EditProfileFragment : Fragment() {
...
-                            .placeholder(icon)
-                            .transform(CircleTransform())
-                            .into(rootView.profilePhoto)
+                            Picasso.get()
+                                .load(imageUrl)
+                                .placeholder(icon)
+                                .transform(CircleTransform())
+                                .into(rootView.profilePhoto)
+
+                        }
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: Fix indentation

Comment (trancenoid) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: @iamareebjamal Done!

File: app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt [hunk 4]
```diff
@@ -55,14 +55,16 @@ class EditProfileFragment : Fragment() {
...
                 rootView.lastName.setText(userLastName)
-                context?.let { ctx ->
-                    val drawable = AppCompatResources.getDrawable(ctx, R.drawable.ic_account_circle_grey_24dp)
-                    drawable?.let { icon ->
-                        Picasso.get()
-                            .load(imageUrl)
-                            .placeholder(icon)
-                            .transform(CircleTransform())
-                            .into(rootView.profilePhoto)
+                if(!imageUrl.isEmpty()) { // picasso requires the imageUrl to be non empty
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: Space after if

Comment (trancenoid) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: @iamareebjamal Sorry, missed that. I have removed it

Comment (trancenoid) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: @iamareebjamal is it correctly done now ?

File: app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt [hunk 5]
```diff
@@ -55,14 +55,16 @@ class EditProfileFragment : Fragment() {
...
-                    drawable?.let { icon ->
-                        Picasso.get()
-                            .load(imageUrl)
-                            .placeholder(icon)
-                            .transform(CircleTransform())
-                            .into(rootView.profilePhoto)
+                if (!imageUrl.isEmpty()) { // picasso requires the imageUrl to be non empty
+                    context?.let { ctx ->
+                        val drawable = AppCompatResources.getDrawable(ctx, R.drawable.ic_account_circle_grey_24dp)
+                        drawable?.let{ icon ->
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: Space after let

Comment (trancenoid) [reply app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt]: @iamareebjamal Done

**Comment by iamareebjamal** [comment]
OK, now just change the PR title according to the commit guidelines and we are done
