### PR TITLE
fix: Authenticate user by start activity for results in attendee section

### LINKED ISSUE #770: Bugs in Attendee details section after authentication
**Describe the bug**
In attendee details fragment - 
- Unnecessary navigation bar display after authentication
- Title not changing after returning back

**To Reproduce**
1. Logout
2. Register for a ticket
3. After authentication see the bugs

**Screenshots**
<p align="center">
 
 
</p>

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### LINKED ISSUE #791: App crashes after opening attendee section
**Describe the bug**
After latest commit, app crashes while opening attendee section - 

`kotlin.UninitializedPropertyAccessException: lateinit property paymentCurrency has not been initialized
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)`

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #770 
Fixes #791 

Authenticate user by startActivityForResult and handle result in the attendee fragment. No need to start new main activity, set the fragment and get bundles.

### CODE REVIEW

**Comment by liveHarshit** [comment]
Build successful.

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 1]
```diff
@@ -269,123 +270,126 @@ class AttendeeFragment : Fragment() {
...
+        else {
+            redirectToLogin()
+            Toast.makeText(context, "You need to log in first!", Toast.LENGTH_LONG).show()
+        }
 
-            attendeeViewModel.progress.observe(this, Observer {
-                it?.let { Utils.showProgressBar(rootView.progressBarAttendee, it) }
-            })
+        attendeeViewModel.ticketSoldOut.observe(this, Observer
+        {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Move to previous line

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 2]
```diff
@@ -77,12 +74,6 @@ class MainActivity : AppCompatActivity() {
                 navigation.selectedItemId = navigation_search
             }
 
-            if (bundle.getBoolean(LAUNCH_ATTENDEE)) {
-                val fragment = AttendeeFragment()
-                fragment.arguments = bundle
-                loadFragment(supportFragmentManager, fragment, rootLayout.id)
-            }
-
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: How is this case handled?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: > How is this case handled?

It is not required now. Because here we start auth activity from the fragment, authenticate user, finish the auth activity and continue with the attendee fragment. No need to open main activity, pass bundle and load fragment again with same data.

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt (hunk 1 above)
Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Updated

**Comment by liveHarshit** [comment]
@iamareebjamal Conflicts resolved. Please do review.
