### PR TITLE
fix: Replace google map with mapbox.

### LINKED ISSUE #756: Empty map section in event details
**Describe the bug**

Map section remains empty in event details. Sometimes placeholder appears but then disappears instantly. 

**To Reproduce**

1. Go to Events.
2. Click on any event.
3. Scroll down to map section.
4. The section is empty. But clicking there opens Google Maps.

**Expected behavior**

Map of the location should have been displayed.

**Screenshots**

screenshot_2018-12-22-13-20-21-433_com eventyay attendee

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

### LINKED ISSUE #1132: Extra useless space in Event Details
**Describe the bug**
Their is a huge extra space in Event Details page
**To Reproduce**
Event List -> Select a event

**Expected behavior**
No useless space should be present
**Actual Behaviour**
Space is present
**Would you like to work on the issue?**
- [x] Yes

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #756 
Fixes #1132 

Changes: Replaced googlemap with mapbox.

Screenshots for the change:
image

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt [hunk 1]
```diff
@@ -47,13 +47,11 @@ class EventDetailsViewModel(private val eventService: EventService) : ViewModel(
...
         // location handling
-        val mapUrlInitial = "https://maps.googleapis.com/maps/api/staticmap?center="
-        val mapUrlProperties = "&zoom=12&size=1200x390&markers=color:red%7C"
-        val mapUrlMapType = "&markers=size:mid&maptype=roadmap"
-
-        val latLong: String = "" + event.latitude + "," + event.longitude
-
-        return mapUrlInitial + latLong + mapUrlProperties + latLong + mapUrlMapType
+        val MAPBOX_STATIC_MAP_KEY =
+            "pk.eyJ1IjoiYW5nbWFzMSIsImEiOiJjanNqZDd0N2YxN2Q5NDNuNTBiaGt6eHZqIn0.BCrxjW6rP_OuOuGtbhVEQg"
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt]: Add in build.gradle

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt]: Okay

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt]: done

File: app/build.gradle [hunk 2]
```diff
@@ -9,6 +9,7 @@ apply plugin: 'kotlin-android-extensions'
 apply plugin: 'androidx.navigation.safeargs'
 
 def STRIPE_API_TOKEN = System.getenv('STRIPE_API_TOKEN') ?: "YOUR_API_KEY"
+def MAPBOX_KEY = '"pk.eyJ1IjoiYW5nbWFzMSIsImEiOiJjanNqZDd0N2YxN2Q5NDNuNTBiaGt6eHZqIn0.BCrxjW6rP_OuOuGtbhVEQg"'
```
Comment (iamareebjamal) [inline app/build.gradle]: Define it like the stripe token so that we can replace it in the build system, but instead of `"YOUR_API_KEY"`, keep this API key

File: app/build.gradle [hunk 3]
```diff
@@ -9,7 +9,7 @@ apply plugin: 'kotlin-android-extensions'
 apply plugin: 'androidx.navigation.safeargs'
 
 def STRIPE_API_TOKEN = System.getenv('STRIPE_API_TOKEN') ?: "YOUR_API_KEY"
-def MAPBOX_KEY = '"pk.eyJ1IjoiYW5nbWFzMSIsImEiOiJjanNqZDd0N2YxN2Q5NDNuNTBiaGt6eHZqIn0.BCrxjW6rP_OuOuGtbhVEQg"'
+def MAPBOX_KEY = '"'+System.getenv('MAPBOX_KEY')+'"' ?: '"pk.eyJ1IjoiYW5nbWFzMSIsImEiOiJjanNqZDd0N2YxN2Q5NDNuNTBiaGt6eHZqIn0.BCrxjW6rP_OuOuGtbhVEQg"'
```
Comment (angmas1) [inline app/build.gradle]: Did as you said @iamareebjamal now I'm getting null as value of key. Sorry, can you tell me how to initialize the value of environment variable. I don't know how to do that.

Comment (iamareebjamal) [reply app/build.gradle]: It shouldn't be null. If it is not defined in the environment, it should fallback to this key

Comment (angmas1) [reply app/build.gradle]: Even I thought so but it's not working

Comment (iamareebjamal) [reply app/build.gradle]: Remove `'"'+` before and after

Comment (angmas1) [reply app/build.gradle]: resolved

**Comment by iamareebjamal** [comment]
Working now?

**Comment by angmas1** [comment]
Yes
