### PR TITLE
fix: use navigation arch to redirect to events when logout 

### LINKED ISSUE #968: use navigation arch to redirect to events when logout
**Describe the bug**
After User logout navigation arch should be used to redirect to events

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Fixes #968

GIF 
gif-190127_164323

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt [hunk 1]
```diff
@@ -47,8 +46,8 @@ class ProfileFragment : Fragment() {
         findNavController(rootView).navigate(R.id.loginFragment, bundle, getAnimFade())
     }
 
-    private fun redirectToMain() {
-        startActivity(Intent(activity, MainActivity::class.java).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP))
+    private fun redirectToEvents() {
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: `redirectToEventsFragment`

Comment (GOVINDDIXIT) [reply app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt]: renamed same in OrderCompletedFragment also
