### PR TITLE
fix: Check for device location settings

### LINKED ISSUE #1971: Location progress is continued showing
**Describe the bug**
Location progress is continued showing if the device location is off

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1971

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt [hunk 1]
```diff
@@ -105,6 +111,19 @@ class SearchLocationFragment : Fragment() {
         }
     }
 
+    private fun isLocationEnabled(): Boolean {
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt]: This logic can be re used. Using it from a  util function would be better

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt [hunk 2]
```diff
@@ -204,4 +207,17 @@ object Utils {
             else -> cardType.NONE
         }
     }
+
+    fun checkLocationSettings(context: Context): Boolean {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: `checkLocationSettings` is a verb, hence, this function should return nothing

If you want this to return boolean, rename to `isLocationEnabled`

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: Updated
