### PR TITLE
fix: Social Links and Similar Events get refetched when event is favorited

### LINKED ISSUE #256: Social Links and Similar Events get refetched when event is favorited
Social Links and Similar events are being refetched when event is favorited using toolbar icon or fab icon present in Similar events. This should not occur

Working on it :+1:

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #256 

Changes: Stopped re fetching of similar events and organization details on setting favorite.

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt [hunk 1]
```diff
@@ -70,6 +70,7 @@ class EventDetailsFragment : Fragment() {
     private val LINE_COUNT: Int = 3
     private var menuActionBar: Menu? = null
     private var title: String = ""
+    private var runonce: Boolean = true
```
Comment (dreadpool2) [inline app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt]: use camel case (runOnce)

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt]: Okay
