### PR TITLE
fix: App exit on back pressed

### LINKED ISSUE #596: App exit when back button is pressed
### Issue

- When the back button is pressed in any fragment cause exit the app.
- App also exit when back button is pressed after search 

### Solution 
Like Eventbright - 

- Set event fragment when back button is pressed form another fragment.
- Close search view when back button is pressed after search

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #596

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 1]
```diff
@@ -111,4 +112,31 @@ class MainActivity : AppCompatActivity() {
...
                 .commit()
     }
+
+    override fun onBackPressed() {
+        val currentFragmentClass = this.supportFragmentManager.findFragmentById(R.id.frameContainer).javaClass
+        when (currentFragmentClass) {
+            SearchFragment().javaClass -> {
+                loadFragment(EventsFragment())
+                supportActionBar?.title = "Events"
+                navigation.selectedItemId = navigation_events
```
Comment (simarsingh24) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: you are repeating the same code, think of some other way to acheive it

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Can I create a method for set event fragment?

Comment (simarsingh24) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: instead, you may use the logic `when currentFragmentClass is not EventFragment` since you want to get back to EventFragment in all case except current being EventFragment

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: > instead, you may use the logic `when currentFragmentClass is not EventFragment` since you want to get back to EventFragment in all case except current being EventFragment

But if we want another condition in future like, need to load another fragment in a special case then it was a problem there. Should I change it?

Comment (simarsingh24) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: then it would be changed accordingly for now just change it :)

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 2]
```diff
@@ -111,4 +112,21 @@ class MainActivity : AppCompatActivity() {
...
                 .commit()
     }
+
+    override fun onBackPressed() {
+        val currentFragmentClass = this.supportFragmentManager.findFragmentById(R.id.frameContainer).javaClass
+        when (currentFragmentClass) {
+            SearchFragment().javaClass -> setEventFragment()
+            FavoriteFragment().javaClass -> setEventFragment()
+            OrdersUnderUserFragment().javaClass -> setEventFragment()
+            ProfileFragment().javaClass -> setEventFragment()
```
Comment (simarsingh24) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: why not just do it when currentFragmentClass is not EventFragment, if in future we want some different functionality we can change it

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: > why not just do it when currentFragmentClass is not EventFragment, if in future we want some different functionality we can change it

Updated.

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 3]
```diff
@@ -111,4 +112,13 @@ class MainActivity : AppCompatActivity() {
...
                 .commit()
     }
+
+    override fun onBackPressed() {
+        val currentFragmentClass = this.supportFragmentManager.findFragmentById(R.id.frameContainer).javaClass
+        if(currentFragmentClass != EventsFragment().javaClass) {
+            loadFragment(EventsFragment())
+            supportActionBar?.title = "Events"
+            navigation.selectedItemId = navigation_events
+        }
```
Comment (simarsingh24) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: else super on back pressed

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 4]
```diff
@@ -111,4 +112,13 @@ class MainActivity : AppCompatActivity() {
                 .replace(R.id.frameContainer, fragment)
                 .commit()
     }
+
+    override fun onBackPressed() {
+        val currentFragmentClass = this.supportFragmentManager.findFragmentById(R.id.frameContainer).javaClass
+        if(currentFragmentClass != EventsFragment().javaClass) {
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: space after if
Rest LGTM ! :+1:

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt (hunk 3 above)
Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Oops, sorry for that. Let me update.

**Comment by liveHarshit** [comment]
Updated.

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 5]
```diff
@@ -111,4 +112,15 @@ class MainActivity : AppCompatActivity() {
                 .replace(R.id.frameContainer, fragment)
                 .commit()
     }
+
+    override fun onBackPressed() {
+        val currentFragmentClass = this.supportFragmentManager.findFragmentById(R.id.frameContainer).javaClass
+        if (currentFragmentClass != EventsFragment().javaClass) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Check using `instanceOf` 

Secondly, you are instantiating EventsFragment here - `EventsFragment().javaClass` Why?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: My question is that why are you instantiating the fragment? Why are `()` after the class name?

Nevertheless, this won't be needed when you use `instanceOf`

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Read about static fields of a class. However, implement this by `is` keyword of Kotlin

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 6]
```diff
@@ -111,4 +112,15 @@ class MainActivity : AppCompatActivity() {
                 .replace(R.id.frameContainer, fragment)
                 .commit()
     }
+
+    override fun onBackPressed() {
+        val currentFragment = this.supportFragmentManager.findFragmentById(R.id.frameContainer)
+        if (currentFragment !is EventsFragment) {
+            loadFragment(EventsFragment())
+            supportActionBar?.title = "Events"
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: This should not be needed

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: What exactly, can't get it.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: `supportActionBar?.title = "Events"`

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: Updated
