### PR TITLE
fix: Progress dialog is continued showing on error in attendee fragment

### LINKED ISSUE #1946: Progress bar is continued showing on throwing error
**Describe the bug**
The progress bar is continued showing on throwing an error in attendee fragment.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1946

### CODE REVIEW

**Comment by ShridharGoel** [comment]
@liveHarshit Isn't the `mutableProgress.value` required to be set to `false` in this case too?

```
if (it.message.equals(HttpErrors.CONFLICT)) {
    mutableTicketSoldOut.value = true
}
```

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt [hunk 1]
```diff
@@ -179,6 +179,7 @@ class AttendeeViewModel(
                     } else {
                         mutableMessage.value = resource.getString(R.string.create_attendee_fail_message)
                         Timber.d(it, "Failed")
+                        mutableProgress.value = false
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt]: Just move the statement out if it is in both if and else clause

**Comment by liveHarshit** [comment]
> @liveHarshit Isn't the `mutableProgress.value` required to be set to `false` in this case too?
> 
> ```
> if (it.message.equals(HttpErrors.CONFLICT)) {
>     mutableTicketSoldOut.value = true
> }
> ```

Yes it should. Sorry, I did it by mistake.
