### PR TITLE
fix: Improve AttendeeFragment

### LINKED ISSUE #1885: Multiple small problems in AttendeeFragment
**Describe the bug**
- The naming of the event contains time while the text below also displays the time of the event as well (redundant)
- Time displayed for event is not logical (Date is displayed twice for event with same days)
- Remove billing information section for free events
- Remove alert dialog on creating order
- Add loading progress dialog on ordering ticket
- Pop up message on not all fields are filled

**Additional context**
Discussion on yesterday meeting https://docs.google.com/document/d/169tq2sr7lF_RnWnXA7hGVEIhQsrHT9tQjB32hHdlUL8/edit

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anhanh11001**
Details:
- Set up more logically time display of event
- Remove card type selector as it doesn't matter that much. Stripe automatically determine card type based on card number provided
- Hide billing information for free tickets
- Show pop up message for "required fields should be filled"
- Remove confirm dialog on ordering ticket (based on Eventbrite)

Fixes #1885

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 1]
```diff
@@ -742,37 +699,30 @@ class AttendeeFragment : Fragment(), ComplexBackPressFragment {
                 return@setOnClickListener
             }
 
-            if (!checkRequiredFields()) return@setOnClickListener
+            if (!checkRequiredFields()) {
+                rootView.snackbar(R.string.fill_required_fields_message)
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Have you tested it because `NestedScrollView` can host only one direct child?

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: I will check it again and comment later

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Well it still shows the message here. Is it what you mean?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: Okay, It is fine then. Sometimes the app crashes when NestedScrollView is root layout and we set snackbar msg on it.
