### PR TITLE
fix: App crash on selecting register when not logged in

### LINKED ISSUE #276: app crashes on selecting tickets if not logged in
working on it 👍

### PR DESCRIPTION
**Pull request by simarsingh24**
fixes #276

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt [hunk 1]
```diff
@@ -52,49 +52,48 @@ class AttendeeFragment : Fragment() {
...
+
+                        attendeeFragmentViewModel.createAttendee(attendee)
+                    }
                 }
             }
+        } else {
+            redirectToLogin()
+            Toast.makeText(context, "You need to log in first!", Toast.LENGTH_LONG).show()
         }
-
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt]: not required
