### PR TITLE
fix: stop flickering of events on backpress

### LINKED ISSUE #75: Events UI is flickering on loading events
Working on it

### PR DESCRIPTION
**Pull request by nikit19**
fixes #75 

ezgif com-video-to-gif 6

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt [hunk 1]
```diff
@@ -79,6 +80,9 @@ class EventsFragment : Fragment() {
         val lastVisible = linearLayoutManager.findLastVisibleItemPosition()
         val itemsChanged = lastVisible - firstVisible + 1 // + 1 because we start count items from 0
         val start = if (firstVisible - itemsChanged > 0) firstVisible - itemsChanged else 0
-        eventsRecyclerAdapter.notifyItemRangeChanged(start, itemsChanged + itemsChanged)
+        if (!eventsViewModel.loadEventsAgain)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: When will it ever get called

Comment (nikit19) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: The default value is false. So every time the app starts, the animation is seen or if the user clicks on Events in the bottom navigation bar ,the animation is seen.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: The boolean variable name is confusing. Please change to a proper name and comment wherever the vale is changed

**Comment by nikit19** [comment]
PR updated

File: app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt [hunk 2]
```diff
@@ -44,7 +44,7 @@ class EventsFragment : Fragment() {
                 val bundle = Bundle()
                 bundle.putLong(fragment.EVENT_ID, eventID)
                 fragment.arguments = bundle
-                eventsViewModel.loadEventsAgain = true
+                eventsViewModel.loadEventsWithAnimation = false // No slide up animation
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: Explain why it is being set to false here

Comment (nikit19) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: if you open the event details fragment and return to the events fragments the UI flickers.
I am using this boolean for that particular case

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: I meant explain this in comment. Your comment here is obvious. Comments are used for non-obvious things

Comment (nikit19) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: comment removed

File: app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt [hunk 3]
```diff
@@ -44,6 +44,7 @@ class EventsFragment : Fragment() {
                 val bundle = Bundle()
                 bundle.putLong(fragment.EVENT_ID, eventID)
                 fragment.arguments = bundle
+                eventsViewModel.loadEventsWithAnimation = false
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: Rather than explaining that in the comment, you removed the comment altogether

Comment (nikit19) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: Meaningful comment added

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: Add the comment above this statement

Comment (nikit19) [reply app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt]: PR updated
