### PR TITLE
moved date format functions to EventUtils

### LINKED ISSUE #153: move date formating functions to EventUtils
Formating functions inside `AboutEventViewModel` should be moved ot eventUtils
```
 fun getAboutEventFormattedDate(date: String): String{
        val dateString = EventUtils.getLocalizedDateTime(date)
        //Format Month
        val lowerCaseMonth = dateString.dayOfWeek.toString().toLowerCase()
        val formatMonth = (lowerCaseMonth.substring(0, 1).toUpperCase() + lowerCaseMonth.substring(1)).substring(0, 3)
        //Format Day
        val lowerCaseDay = dateString.month.toString().toLowerCase()
        val formatDay = (lowerCaseDay.substring(0, 1).toUpperCase() + lowerCaseDay.substring(1)).substring(0, 3)

        return formatMonth + ", " + formatDay + " " + dateString.dayOfMonth
    }

    fun getAboutEventFormattedTime(date: String): String{
        var testDate =  Date()
        val dateString = date.replace("T"," ")
        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        try {
            testDate = dateFormat.parse(dateString)
        } catch (e: ParseException) {
            Timber.e(e,"Error Parsing Date")
        }
        val dateFormatFinal = SimpleDateFormat("hh:mm a Z", Locale.getDefault())
        return dateFormatFinal.format(testDate)
    }
```
Instead of creating same funtions for #135 we can put these in EventUtils and call them so that these functions will be accessible from everywhere
working on it 👍

### PR DESCRIPTION
**Pull request by simarsingh24**
fixes #153

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 1]
```diff
@@ -63,4 +63,29 @@ object EventUtils {
...
+    fun getAboutEventFormattedDate(date: String): String{
+        val dateString = EventUtils.getLocalizedDateTime(date)
+        //Format Month
+        val lowerCaseMonth = dateString.dayOfWeek.toString().toLowerCase()
+        val formatMonth = (lowerCaseMonth.substring(0, 1).toUpperCase() + lowerCaseMonth.substring(1)).substring(0, 3)
+        //Format Day
+        val lowerCaseDay = dateString.month.toString().toLowerCase()
+        val formatDay = (lowerCaseDay.substring(0, 1).toUpperCase() + lowerCaseDay.substring(1)).substring(0, 3)
+
+        return formatMonth + ", " + formatDay + " " + dateString.dayOfMonth
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Properly use date formatting instead of substringing

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 2]
```diff
@@ -63,4 +63,29 @@ object EventUtils {
...
+        var testDate =  Date()
+        val dateString = date.replace("T"," ")
+        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
+        try {
+            testDate = dateFormat.parse(dateString)
+        } catch (e: ParseException) {
+            Timber.e(e,"Error Parsing Date")
+        }
+        val dateFormatFinal = SimpleDateFormat("hh:mm a Z", Locale.getDefault())
+        return dateFormatFinal.format(testDate)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Same here

No idea how it got merge

Comment (simarsingh24) [reply app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: i wil change this 😄

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 3]
```diff
@@ -63,4 +63,26 @@ object EventUtils {
             }
         return testDate.time
     }
+
+    fun getFormattedDate(date: ZonedDateTime): String{
+        var dateString = String()
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: why don't you use lateinit

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 4]
```diff
@@ -63,4 +63,26 @@ object EventUtils {
...
+        try {
+            dateString = dateFormat.format(date)
+        } catch (e: IllegalArgumentException) {
+            Timber.e(e,"Error formatting Date")
+        }
+        return dateString
+    }
+
+    fun getFormattedTime(date: ZonedDateTime): String {
+        var timeString = String()
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: here too

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 5]
```diff
@@ -63,4 +63,26 @@ object EventUtils {
...
+
+    fun getFormattedDate(date: ZonedDateTime): String{
+        lateinit var dateString : String
+        val dateFormat: DateTimeFormatter = DateTimeFormatter.ofPattern("EEE, MMM d")
+        try {
+            dateString = dateFormat.format(date)
+        } catch (e: IllegalArgumentException) {
+            Timber.e(e,"Error formatting Date")
+        }
+        return dateString
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: This will throw exception if used in case of exception

Comment (simarsingh24) [reply app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: should i remove try catch then

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: No, send empty string if there's an exception

Comment (simarsingh24) [reply app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: okay

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 6]
```diff
@@ -52,15 +52,37 @@ object EventUtils {
...
-        val dateString = date.replace("T"," ")
-            val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
-            try {
-                testDate = dateFormat.parse(dateString)
-            } catch (e: ParseException) {
-                Timber.e(e,"Error Parsing Date")
-            }
+    fun getTimeInMilliSeconds(date: String): Long {
+        var testDate = Date()
+        val dateString = date.replace("T", " ")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Wrong logic

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 7]
```diff
@@ -52,15 +52,37 @@ object EventUtils {
...
-        var testDate =  Date()
-        val dateString = date.replace("T"," ")
-            val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
-            try {
-                testDate = dateFormat.parse(dateString)
-            } catch (e: ParseException) {
-                Timber.e(e,"Error Parsing Date")
-            }
+    fun getTimeInMilliSeconds(date: String): Long {
+        var testDate = Date()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Why

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 8]
```diff
@@ -52,15 +52,37 @@ object EventUtils {
...
+            Timber.e(e, "Error Parsing Date")
+        }
         return testDate.time
     }
+
+    fun getFormattedDate(date: ZonedDateTime): String {
+        var dateString = ""
+        val dateFormat: DateTimeFormatter = DateTimeFormatter.ofPattern("EEE, MMM d")
+        try {
+            dateString = dateFormat.format(date)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Simply return

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 9]
```diff
@@ -52,15 +52,37 @@ object EventUtils {
...
+        } catch (e: IllegalArgumentException) {
+            Timber.e(e, "Error formatting Date")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: Return empty here

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt (hunk 6 above)
Comment (simarsingh24) [reply app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: i havent added this part of code just refacoted it. however i will change these things

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 10]
```diff
@@ -52,15 +49,28 @@ object EventUtils {
...
-        val dateString = date.replace("T"," ")
-            val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
-            try {
-                testDate = dateFormat.parse(dateString)
-            } catch (e: ParseException) {
-                Timber.e(e,"Error Parsing Date")
-            }
-        return testDate.time
+    fun getTimeInMilliSeconds(dateString: String): Long {
+        var date: ZonedDateTime = getLocalizedDateTime(dateString)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: why var

**Comment by simarsingh24** [comment]
@iamareebjamal this is a blocker for my next PR, if no changes are needed please merge this :)
