### PR TITLE
refractor: Replace all hard-coded string messages

### LINKED ISSUE #1256: Extract all hard-coded strings
**Describe the bug**
There are still some hard-coded strings in the code base so I will move all of them to the res/values/strings file

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anhanh11001**
Details:
- Resolve merge conflicts
- Some Bengali strings are not translated as I don't know how to do that, so I put "need translations"
- Strings are extracted using Resource class

Fixes #1256

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please resolve conflicts

**Comment by anhanh11001** [comment]
@iamareebjamal I have resolved merge conflicts, please take a look

**Comment by anhanh11001** [comment]
@iamareebjamal please take a look, I have updated another solution on extracting resource in ViewModel

File: app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt [hunk 1]
```diff
@@ -24,7 +26,7 @@ class AboutEventViewModel(private val eventService: EventService) : ViewModel()
 
     fun loadEvent(id: Long) {
         if (id.equals(-1)) {
-            mutableError.value = "Error fetching event"
+            mutableError.value = OpenEventGeneral.appResource.getString(R.string.error_fetching_event_message)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt]: This is still using resources in viewmodel

Easy way to check if you are using resources in ViewModel - Instantiate the ViewModel in a test and run all methods

If the test crashes, you are using Android class in ViewModel

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt]: I understand that now and referencing string resource inside ViewModel is not safe, so I don't find a way to extract those strings inside ViewModel.

And I have read the Android documentation, and it said "if the ViewModel needs the Application context, it can extend the AndroidViewModel class and have a constructor that receives the Application in the constructor". Should I use this technique to extract the hard-coded strings inside the view model into res/values/strings file or I should leave them unextracted?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt]: https://github.com/fossasia/open-event-android/blob/development/app/src/main/java/org/fossasia/openevent/general/data/Resource.kt

File: app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt [hunk 2]
```diff
@@ -83,36 +85,36 @@ class AttendeeViewModel(
...
+        month.add(Resource().getString(R.string.march) ?: "March")
+        month.add(Resource().getString(R.string.april) ?: "April")
+        month.add(Resource().getString(R.string.may) ?: "May")
+        month.add(Resource().getString(R.string.june) ?: "June")
+        month.add(Resource().getString(R.string.july) ?: "July")
+        month.add(Resource().getString(R.string.august) ?: "August")
+        month.add(Resource().getString(R.string.september) ?: "September")
+        month.add(Resource().getString(R.string.october) ?: "October")
+        month.add(Resource().getString(R.string.november) ?: "November")
+        month.add(Resource().getString(R.string.december) ?: "December")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt]: Redundant

File: app/src/main/res/values-bn-rIN/strings.xml [hunk 3]
```diff
@@ -185,4 +185,72 @@
...
+    <string name="login_fail_message">Needs translation</string>
+    <string name="email_not_in_server_message">Needs translation</string>
+    <string name="email_sent">Needs translation</string>
+    <string name="discover_pay_message">Needs translation</string>
+    <string name="diners_pay_message">Needs translation</string>
+    <string name="unionpay_pay_message">Needs translation</string>
+    <string name="postal_code">Needs translation</string>
+    <string name="payment_info">Needs translation</string>
+    <string name="removed_from_liked">Needs translation</string>
+    <string name="undo">Needs translation</string>
```
Comment (iamareebjamal) [inline app/src/main/res/values-bn-rIN/strings.xml]: Remove all of these

**Comment by iamareebjamal** [comment]
All approved PRs beyond this point will be merged after release
