### PR TITLE
fixes #439

### LINKED ISSUE #439: App crashes when a bad API URL is entered
When I add an arbitary wrong url in the app generator like /api/v1.com, the app crashes. This error should be handled graciously.

### PR DESCRIPTION
**Pull request by mananwason**
@the-dagger Please review and merge

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/api/Urls.java [hunk 1]
```diff
@@ -46,6 +50,12 @@ public static String getBaseUrl() {
     }
 
     public static void setBaseUrl(String baseUrl) {
-        BASE_URL = baseUrl;
+        if (URLUtil.isValidUrl(baseUrl)) {
```
Comment (the-dagger) [inline android/app/src/main/java/org/fossasia/openevent/api/Urls.java]: So basically anything that is a valid URL will be qualified as good to go here tight?
So what if I use www.google.com here?
It is a valid URL but is not a valid API.
@mananwason

Comment (mananwason) [inline android/app/src/main/java/org/fossasia/openevent/api/Urls.java]: Yes @the-dagger, you are correct. We can never know if an api is correct without actually making a request. This PR focuses on invalid api urls which was making the app crash

Comment (the-dagger) [inline android/app/src/main/java/org/fossasia/openevent/api/Urls.java]: Ok cool, got it.
