### PR TITLE
fix: After coming back from result detail, search result come back to the top, not current position #1150

### LINKED ISSUE #1150: After coming back from result detail, search result come back to the top, not current position
**Describe the bug**
When users try click on a search result and then click back button, the search result doesn't stay at the same position but get to the top

** Images & Gif **
Gif link: https://i.ibb.co/Qmb3Cwv/video-1550686001.gif (file too large, cannot upload to issue)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Nokia 7 Plus|
|Android Version| Android 9 API 28 |

**Would you like to work on the issue?**

<b>Yes </b>

### PR DESCRIPTION
**Pull request by anhanh11001**
Details: 
After coming from EventDetailsFragment, the SearchResultFragment doesn't retain the old position. Adding id for NestedScrollView will make Android automatically retain the current position

Fixes: #1150

### CODE REVIEW

**Comment by liveHarshit** [comment]
Any special reason for closing PR #1182 and create a new one?

File: app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt [hunk 1]
```diff
@@ -88,8 +90,20 @@ class SearchLocationFragment : Fragment() {
...
+            val bundle = Bundle()
+            bundle.putBoolean(NEW_SEARCH, true)
+            val navOptions = NavOptions.Builder()
+                .setEnterAnim(R.anim.slide_in_left)
+                .setExitAnim(R.anim.slide_out_right)
+                .setPopEnterAnim(R.anim.slide_in_left)
+                .setPopExitAnim(R.anim.slide_out_right)
+                .setPopUpTo(R.id.eventsFragment, true)
+                .build()
+            Navigation.findNavController(rootView).navigate(R.id.eventsFragment, bundle, navOptions)
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt]: Not a good solution. It was better earlier. Can you please find another way for it? Reset looks good.

Comment (anhanh11001) [reply app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt]: @liveHarshit I have updated a better solution. haha, I was stupid before, this is actually a much simpler issue.

File: app/src/main/res/layout/fragment_search_results.xml [hunk 2]
```diff
@@ -29,6 +29,7 @@
     </LinearLayout>
 
     <androidx.core.widget.NestedScrollView
+        android:id="@+id/searchResultsNestedScrollView"
```
Comment (liveHarshit) [inline app/src/main/res/layout/fragment_search_results.xml]: Can you please explain, how defining an id solve the issue?

Comment (anhanh11001) [reply app/src/main/res/layout/fragment_search_results.xml]: @liveHarshit Well, in short, this is Android View State Storing Mechanism (to retain an amount of information/state if we provide it an id). So for instance, if you're having an EditText and some text in it, I believe the text is also retained after screen rotation if we provide it with an id.

So this is also the way current EventsFragment restoring its position after coming back from EventDetailsFragment.
