### PR TITLE
fix: Disable text fields and buttons during progress.

### LINKED ISSUE #1045: Disable text fields and button during progress
**Describe the bug**
Disable text field and buttons during progress in login and sign up fragments. Because during sign in or smart authentication it is not a good user experience to make edit field accessible.

Better solution is to use an overlapping progress bar. 

**Would you like to work on the issue?**

- Other: Open for all

### PR DESCRIPTION
**Pull request by angmas1**
Fixes #1045 

Changes: When sign-up/login buttons are clicked, the button gets replaced with progress bar and the edit text fields get disabled.

Screenshots for the change:
ezgif com-video-to-gif 1
ezgif com-video-to-gif

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 1]
```diff
@@ -14,9 +14,7 @@ import androidx.fragment.app.Fragment
 import androidx.lifecycle.Observer
 import androidx.navigation.Navigation.findNavController
 import com.google.android.material.snackbar.Snackbar
-import kotlinx.android.synthetic.main.fragment_login.email
-import kotlinx.android.synthetic.main.fragment_login.loginButton
-import kotlinx.android.synthetic.main.fragment_login.password
+import kotlinx.android.synthetic.main.fragment_login.*
```
Comment (GOVINDDIXIT) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: avoid wild card imports

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: okay

**Comment by angmas1** [comment]
@nikit19 corrected please review.

**Comment by liveHarshit** [comment]
Like that -  no need to handle visibality and disable text fields. 
<p align="center">
 
</p>

**Comment by angmas1** [comment]
Okay

**Comment by angmas1** [comment]
> Like that - no need to handle visibality and disable text fields.
> 
> 

image

Done!

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 2]
```diff
@@ -56,6 +56,11 @@ class LoginFragment : Fragment() {
         setHasOptionsMenu(true)
         showSnackbar()
 
+        val dialog = Dialog(context)
+        dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
+        dialog.setCancelable(false)
+        dialog.setContentView(R.layout.dialog_progress)
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Can you move dialog logic to utils, so we can display it anytime by passing context?

**Comment by iamareebjamal** [comment]
The dialog is too large

**Comment by angmas1** [comment]
Okay, moving dialog to utils and making it smaller.

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 2 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: done

**Comment by angmas1** [comment]
image

image

**Comment by angmas1** [comment]
ezgif com-video-to-gif 1

ezgif com-video-to-gif

File: app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+        dialog.setCancelable(false)
+        dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
+        dialog.setContentView(R.layout.dialog_progress)
+    }
+
+    fun showOrDismiss(show: Boolean) {
+        if (show && !dialog.isShowing) dialog.show()
+        else if (!show && dialog.isShowing) dialog.dismiss()
+    }
+}
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Utils mean in utils.kt file.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Create a method for the same in utils, no need to create a new file.

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: That won't work because loading dialog is set as non-cancel able, so I have to cancel each dialog box too. So, if I make it into a function then I won't be able to cancel the dialog created on previous call. Hence, I need to create an object of the progressdialog for the entire fragment. This solves the issue. If I make the dialog box cancel able, then the user can just click outside the dialog box which will make it pointless as it won't stop user intervention on login/signup

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: In utils - 
```java
fun showProgressDialog(context: Context, show: Boolean) {
    private val dialog = Dialog(context)
    dialog.setCancelable(false)
    dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
    dialog.setContentView(R.layout.dialog_progress)
    if (show && !dialog.isShowing) dialog.show() else dialog.dismiss()
}
```

And just call the method - 
`Utils.showProgressDialog(requireContext(), true)`
`Utils.showProgressDialog(requireContext(), false)`

Hope it should work.

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: No, it doesn't. That's what I wrote in beginning. The thing is, when this is called it creates a val dialog. So, dialog.isShowing will always return false, because you are referring to the recently created dialog. Hence, you will never be able to close a dialog which was created on previous call and keep on creating new dialogs.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: got it!

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Then you can use it like that - 

In fragment - 
`val dialog = Utils.progressDialog(requireContext())`

In Utils.kt - 

```java
fun progressDialog(context: Context) : Dialog {
    val dialog = Dialog(context)
    dialog.setCancelable(false)
    dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
    dialog.setContentView(R.layout.dialog_progress)
   return dialog
}
```

And visibility can handle inside the fragment.

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 4]
```diff
@@ -81,13 +81,13 @@ class LoginFragment : Fragment() {
         loginViewModel.progress
             .nonNull()
             .observe(this, Observer {
-                handleProgressBar(it)
+            progressDialog.showOrDismiss(it)
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Wrong indentation.

File: app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt (hunk 3 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Can I just move the class to utils.kt?

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Because making a class will be easier when reusing code.

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Moreover, class will use less memory.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: IMO, creating a new class only for a progress dialog is not a good idea, when you can just use a common method instead to remove duplication.

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: @iamareebjamal @nikit19 Please make me correct.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: > Moreover, class will use less memory

1 class will use less memory than no class?

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: What @liveHarshit is suggesting is making a function which initializes the dialog(just like a class constructor.). And handle the logic in the place where the function is called. This is why I'm suggesting a class so that we can handle the logic and initialization in one place. It will be easier then for someone else to use it any where else. Moreover, class will use less memory as in when an object of progressDialog is made, it will use space for one object. Whereas when that initialize method is called it creates an object and then passes it to the object of calling function. Which means for a small amount of time, two objects are in memory. One of calling function and one of initialize function itself. Please correct me if I am wrong.

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 4 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Thanks for pointing out. Will correct.

File: app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt (hunk 3 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: If two classes are invoking two dialogs, the amount of classes are going to be in memory in any case. There is no need to create a class. Make a function which returns a dialog

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Okay

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 4 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Corrected

File: app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt (hunk 3 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/ProgressDialog.kt]: Done

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 5]
```diff
@@ -81,14 +81,14 @@ class LoginFragment : Fragment() {
         loginViewModel.progress
             .nonNull()
             .observe(this, Observer {
-                handleProgressBar(it)
+                handleProgressBar(it, progressDialog)
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Please declare progressDialog as `private lateinit var` before onCreateView and initialize it in onCreateView. So that there is no need to pass progressDialog.

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 6]
```diff
@@ -171,6 +171,11 @@ class LoginFragment : Fragment() {
         smartAuthViewModel.requestCredentials(activity)
     }
 
+    private fun handleProgressBar(show: Boolean, dialog: Dialog) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: No need of this function

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Create an extension function on Dialog `show(boolean) which does this

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 5 above)
Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: As @iamareebjamal suggested, no need to create function

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 6 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Okay

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Done

File: app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt [hunk 7]
```diff
@@ -76,8 +74,8 @@ class SignUpFragment : Fragment() {
         signUpViewModel.progress
             .nonNull()
             .observe(this, Observer {
-                rootView.progressBarSignUp.isVisible = it
-                signUpButton.isEnabled = !it
+                if (it && !progressDialog.isShowing) progressDialog.show()
+                else if (!it && progressDialog.isShowing) progressDialog.dismiss()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Use common method

Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: done

File: app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt [hunk 8]
```diff
@@ -130,6 +128,11 @@ class SignUpFragment : Fragment() {
         Snackbar.make(rootView, R.string.logged_in_automatically, Snackbar.LENGTH_SHORT).show()
     }
 
+    private fun Dialog.show(show: Boolean) {
+        if (show && !this.isShowing) this.show()
+        else if (!show && this.isShowing) this.dismiss()
+    }
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Why are there 2 methods in 2 activities doing the same thing?

File: app/src/main/res/layout/dialog_progress.xml [hunk 9]
```diff
@@ -0,0 +1,21 @@
...
+
+        <TextView
+            android:layout_width="wrap_content"
+            android:layout_height="wrap_content"
+            android:layout_gravity="center"
+            android:paddingRight="@dimen/padding_extreme_large"
+            android:text="Loading..."
+            android:textSize="@dimen/text_size_large" />
+
+</LinearLayout>
```
Comment (iamareebjamal) [inline app/src/main/res/layout/dialog_progress.xml]: Why do we even need this. Isn't progress dialog good enough?

Comment (angmas1) [reply app/src/main/res/layout/dialog_progress.xml]: To setcontentview for dialog.

Comment (iamareebjamal) [reply app/src/main/res/layout/dialog_progress.xml]: Why do we need that?

Comment (angmas1) [reply app/src/main/res/layout/dialog_progress.xml]: This is providing layout for the dialog loading dialog that pops up.

Comment (iamareebjamal) [reply app/src/main/res/layout/dialog_progress.xml]: Again, why do we need a custom layout?

Comment (angmas1) [reply app/src/main/res/layout/dialog_progress.xml]: I don't know any other way of adding a progressBar to a dialog body other than making a custom layout.

File: app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt (hunk 8 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt]: Resolved

File: app/src/main/res/layout/dialog_progress.xml (hunk 9 above)
Comment (iamareebjamal) [reply app/src/main/res/layout/dialog_progress.xml]: https://developer.android.com/reference/android/app/ProgressDialog

Comment (angmas1) [reply app/src/main/res/layout/dialog_progress.xml]: Okay, will implement this.

Comment (angmas1) [reply app/src/main/res/layout/dialog_progress.xml]: done

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt [hunk 10]
```diff
@@ -44,6 +46,21 @@ object Utils {
             .show()
     }
 
+    fun progressDialog(context: Context?): ProgressDialog {
+        /**Initializes progress dialog.*/
+        val dialog = ProgressDialog(context)
+        dialog.setCancelable(false)
+        dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: No need

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt [hunk 11]
```diff
@@ -44,6 +46,21 @@ object Utils {
...
+        dialog.setMessage("Loading...")
+        return dialog
+    }
+
+    fun ProgressDialog.show(show: Boolean) {
+        /**Extends dialog.show()*/
+        if (show && !this.isShowing) this.show()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: Remove  && !this.isShowing

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt [hunk 12]
```diff
@@ -44,6 +46,21 @@ object Utils {
...
+        else if (!show && this.isShowing) this.dismiss()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: Change to else

File: app/src/main/res/values/dimens.xml [hunk 13]
```diff
@@ -26,6 +26,7 @@
     <dimen name="padding_medium">8dp</dimen>
     <dimen name="padding_large">16dp</dimen>
     <dimen name="padding_extra_large">32dp</dimen>
+    <dimen name="padding_extreme_large">128dp</dimen>
```
Comment (iamareebjamal) [inline app/src/main/res/values/dimens.xml]: No need

File: app/src/main/res/values/dimens.xml [hunk 14]
```diff
@@ -49,6 +50,7 @@
     <dimen name="app_bar_height">250dp</dimen>
     <dimen name="fab_margin">16dp</dimen>
     <dimen name="text_margin">16dp</dimen>
+    <dimen name="progress_bar_size">64dp</dimen>
```
Comment (iamareebjamal) [inline app/src/main/res/values/dimens.xml]: No need

Comment (angmas1) [reply app/src/main/res/values/dimens.xml]: done.

File: app/src/main/res/values/dimens.xml (hunk 13 above)
Comment (angmas1) [reply app/src/main/res/values/dimens.xml]: done.

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt (hunk 12 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: done.

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt (hunk 10 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: done.

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt (hunk 11 above)
Comment (angmas1) [reply app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]: done.

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt [hunk 15]
```diff
@@ -44,6 +45,20 @@ object Utils {
             .show()
     }
 
+    fun progressDialog(context: Context?): ProgressDialog {
+        /**Initializes progress dialog.*/
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]:
```suggestion
```

File: app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt [hunk 16]
```diff
@@ -44,6 +45,20 @@ object Utils {
...
+        val dialog = ProgressDialog(context)
+        dialog.setCancelable(false)
+        dialog.setMessage("Loading...")
+        return dialog
+    }
+
+    fun ProgressDialog.show(show: Boolean) {
+        /**Extends dialog.show()*/
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt]:
```suggestion
```
