### PR TITLE
fix: format date and time correctly everywhere

### LINKED ISSUE #240: Format the date and time correctly everywhere
1 In event details the time and date isn't shown in correct format
2 time zone isn't formatted correctly
3 Region of the time zone should also be mentioned
working on it

### PR DESCRIPTION
**Pull request by nikit19**
fixes #240 #210 
changes: format date correctly and show the date and time in a different format if the start and end date are same
Screenshots:
screenshot_20180702-225818
screenshot_20180702-225830

screenshot_20180702-225841
screenshot_20180702-225847

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Add tests for date

File: app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt [hunk 1]
```diff
@@ -58,11 +58,26 @@ class AboutEventActivity : AppCompatActivity(), AppBarLayout.OnOffsetChangedList
...
+                    .append(EventUtils.getFormattedTimeZone(endsAt))
+        } else {
+            aboutEventDetails.text = dateString.append(EventUtils.getFormattedDate(startsAt))
+                    .append(" from ")
+                    .append(EventUtils.getFormattedTime(startsAt))
+                    .append(" to ")
+                    .append(EventUtils.getFormattedTime(endsAt))
+                    .append(" (")
+                    .append(EventUtils.getFormattedTimeZone(endsAt))
+                    .append(")")
```
Comment (srv-twry) [inline app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt]: May be you can encapsulate this somewhere in a helper function. You may need it else where. Even if you don't need it then also there is no need to pollute the Activity with such logic.

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt [hunk 2]
```diff
@@ -119,11 +119,26 @@ class TicketsFragment : Fragment() {
...
+        } else {
+            rootView.time.text = dateString.append(EventUtils.getFormattedDate(startsAt))
+                    .append(" from ")
+                    .append(EventUtils.getFormattedTime(startsAt))
+                    .append(" to ")
+                    .append(EventUtils.getFormattedTime(endsAt))
+                    .append(" (")
+                    .append(EventUtils.getFormattedTimeZone(endsAt))
+                    .append(")")
+        }
```
Comment (srv-twry) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt]: Same. Extract this to a helper and use it everywhere.

**Comment by nikit19** [comment]
@srv-twry there are other places where the timezone is required if I add the `(` brackets in the helper function, the function will not be re usable elsewhere. It's better to create helper function that can be re used. We are anyway adding the formatting logic in the Activities

**Comment by srv-twry** [comment]
I can see two occurence of the bracketed date formatting that you're pointing at. You can may be create two helper functions, one which doesn't add brackets and one which adds brackets. Smaller the activity code, the better it is.

**Comment by nikit19** [comment]
Tests added and another helper function created for timezone 
@iamareebjamal @srv-twry Please review

File: app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt [hunk 3]
```diff
@@ -58,11 +58,25 @@ class AboutEventActivity : AppCompatActivity(), AppBarLayout.OnOffsetChangedList
...
+                    .append(" ")
+                    .append(EventUtils.getFormattedTimeZoneWithBrackets(endsAt))
+        } else {
+            aboutEventDetails.text = dateString.append(EventUtils.getFormattedDate(startsAt))
+                    .append(" from ")
+                    .append(EventUtils.getFormattedTime(startsAt))
+                    .append(" to ")
+                    .append(EventUtils.getFormattedTime(endsAt))
+                    .append(" ")
+                    .append(EventUtils.getFormattedTimeZoneWithBrackets(endsAt))
```
Comment (srv-twry) [inline app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt]: I mean it should be `EventUtils.getFormattedEventDateRange` and it should accept the `startsAt` and `endsAt` variables and then if the startsAt and endsAt dates are same then return the String according to the `if` part otherwise the `else` part. 
The code in activity will just be `EventUtils.getFormattedEventDateRange(startsAt, endsAt)`. All the `if`-`else` will be handled inside the Utils file only.

**Comment by nikit19** [comment]
Moved the entire if else logic to EventUtil
@iamareebjamal @srv-twry Please review

File: app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt [hunk 4]
```diff
@@ -109,4 +112,49 @@ class EventUtilsTest {
...
+    }
+
+    @Test
+    fun `should get formatted date`() {
+        val event = getEvent()
+        val localizedDateTime = getLocalizedDate(event.startsAt)
+        assertEquals("""
+          Monday, Sep 15, 2008
+            """.trimIndent(), EventUtils.getFormattedDate(localizedDateTime))
+    }
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt]: Add more tests for methods you have added

**Comment by nikit19** [comment]
@iamareebjamal added tests for all methods that I have added

File: app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt [hunk 5]
```diff
@@ -109,4 +112,109 @@ class EventUtilsTest {
...
+          Monday, Sep 15
+            """.trimIndent(), EventUtils.getFormattedDateWithoutYear(localizedDateTime))
+    }
+
+    @Test
+    fun `should get formatted date short`() {
+        val event = getEvent()
+        val localizedDateTime = getLocalizedDate(event.startsAt)
+        assertEquals("""
+          Mon, Sep 15,
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt]: Why is there training commas and leading dashes in some of the outputs

File: app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt [hunk 6]
```diff
@@ -109,4 +112,109 @@ class EventUtilsTest {
...
+            """.trimIndent(), EventUtils.getFormattedEventDateTimeRange(startsAt, endsAt))
+    }
+
+    @Test
+    fun `should get formatted date range when start and end date are not same in event details`() {
+        val event = getEvent()
+        val startsAt = getLocalizedDate(event.startsAt)
+        val endsAt = getLocalizedDate(event.endsAt)
+        assertEquals("""
+          - Fri, Sep 19, 07:55 PM IST
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt]: dash

File: app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt [hunk 7]
```diff
@@ -116,14 +116,9 @@ class TicketsFragment : Fragment() {
...
         rootView.organizerName.text = "by ${event.organizerName.nullToEmpty()}"
-        val dateString = StringBuilder()
         val startsAt = EventUtils.getLocalizedDateTime(event.startsAt)
         val endsAt = EventUtils.getLocalizedDateTime(event.endsAt)
-        rootView.time.text = dateString.append(EventUtils.getFormattedDate(startsAt))
-                .append(" - ")
-                .append(EventUtils.getFormattedDate(endsAt))
-                .append(" • ")
-                .append(EventUtils.getFormattedTime(startsAt))
+        rootView.time.text = EventUtils.getFormattedDateTimeRangeDetailed(startsAt,endsAt)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt]: space after comma

File: app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt [hunk 8]
```diff
@@ -63,13 +73,69 @@ object EventUtils {
...
+        }
+    }
+
+    fun getFormattedDateTimeRangeDetailed(startsAt: ZonedDateTime, endsAt: ZonedDateTime): String {
+        try {
+            if (EventUtils.getFormattedDate(startsAt) != EventUtils.getFormattedDate(endsAt))
+                return "${getFormattedDate(startsAt)} at ${getFormattedTime(startsAt)} - ${getFormattedDate(endsAt)} at ${getFormattedTime(endsAt)} (${getFormattedTimeZone(endsAt)})"
+            else
+                return "${getFormattedDate(startsAt)} from ${getFormattedTime(startsAt)} to ${getFormattedTime(endsAt)} (${getFormattedTimeZone(endsAt)})"
+        } catch (e: IllegalArgumentException) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt]: This is at least calculating the date twice

Store the reference to be reused
Similarly for all mehods

File: app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt (hunk 6 above)
Comment (nikit19) [reply app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt]: if I add the dash in the activity I will have to put an if else there.
This is the reason why I am returning it from the EventUtils function
