### PR TITLE
fix: Empty organizer section in Ticket Details (#1308)

### LINKED ISSUE #1308: Empty organizer section in Ticket Details
**Describe the bug**
Empty organizer section in Ticket Details 

**Screenshots**
WhatsApp Image 2019-03-14 at 11 33 17 PM

**Would you like to work on the issue?**

-Yes

### PR DESCRIPTION
**Pull request by aman210697**
Fixes #1308 

Changes: hide organizer label when there is no information about the organizer

Screenshots for the change:
WhatsApp Image 2019-03-14 at 11 52 43 PM(1)
WhatsApp Image 2019-03-14 at 11 52 43 PM

### CODE REVIEW

**Comment by iamareebjamal** [comment]
No wildcard imports

File: app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt [hunk 1]
```diff
@@ -5,16 +5,17 @@ import android.net.Uri
...
+import kotlinx.android.synthetic.main.item_card_order_details.view.date
+import kotlinx.android.synthetic.main.item_card_order_details.view.eventSummary
+import kotlinx.android.synthetic.main.item_card_order_details.view.organizer
 import kotlinx.android.synthetic.main.item_card_order_details.view.map
+import kotlinx.android.synthetic.main.item_card_order_details.view.eventDetails
+import kotlinx.android.synthetic.main.item_card_order_details.view.organizerLabel
 import kotlinx.android.synthetic.main.item_card_order_details.view.name
+import kotlinx.android.synthetic.main.item_card_order_details.view.calendar
 import kotlinx.android.synthetic.main.item_card_order_details.view.orderIdentifier
-import kotlinx.android.synthetic.main.item_card_order_details.view.organizer
```
Comment (ShridharGoel) [inline app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt]: All the above are unnecessary changes.

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt]: IDE itself made wildcard import, so I manually did all imports

Comment (ShridharGoel) [reply app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt]: That's okay, but then you can put them in the same way they were earlier to prevent these deletions and additions from showing up.

Comment (aman210697) [reply app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt]: I will keep in mind next time :)

**Comment by aman210697** [comment]
> No wildcard imports

removed wildcard import, please review @iamareebjamal

**Comment by aman210697** [comment]
> Please revert unnecessary changes.

done :)
