### PR TITLE
fix: welcome back snackbar and remove hardcoded strings

### LINKED ISSUE #914: show welcome back snackbar on redirected fragment
**Describe the bug**

Since post handlers are now removed "welcome back" snackbar should be showed in redirected fragment

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### LINKED ISSUE #915: remove hardcoded strings used for snackbar
**Describe the bug**
remove hardcoded strings used for snackbar

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Fixes #914 
Fixes #915

### CODE REVIEW

File: app/src/main/java/org/fossasia/openevent/general/MainActivity.kt [hunk 1]
```diff
@@ -75,7 +75,9 @@ class MainActivity : AppCompatActivity() {
             R.id.loginFragment,
             R.id.signUpFragment -> {
                 navController.popBackStack(R.id.eventsFragment, false)
-                Snackbar.make(mainFragmentCoordinatorLayout, "Sign in canceled!", Snackbar.LENGTH_SHORT).show()
+                Snackbar.make(
+                    mainFragmentCoordinatorLayout, getString(R.string.sign_in_canceled), Snackbar.LENGTH_SHORT
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/openevent/general/MainActivity.kt]: I don't think getString is required

**Comment by GOVINDDIXIT** [comment]
updated
